import XCTest
@testable import HookahBoss

@MainActor final class PublicFeatureViewModelTests:XCTestCase {
 func testCatalogSearchAndFilterAreOwnedByViewModel()async throws{let mix=sampleMix();let content=CatalogSpy(snapshot:.init(mixes:[mix],articles:[]));let model=MixCatalogViewModel(content:content,library:LibrarySpy());await model.appear();model.search="missing";XCTAssertTrue(model.visibleMixes.isEmpty);model.search="Mix";XCTAssertEqual(model.visibleMixes.count,1);XCTAssertEqual(content.forces,[false])}
 func testCatalogResynchronizesPersonalSignalsAfterReturningFromDetail()async{let mix=sampleMix();let library=LibrarySpy();let model=MixCatalogViewModel(content:CatalogSpy(snapshot:.init(mixes:[mix],articles:[])),library:library);await model.appear();library.ratings[mix.id]=5;library.favoriteMixIDs.insert(mix.id);model.syncLibraryState();XCTAssertEqual(model.catalog.first?.personalRating,5);XCTAssertEqual(model.catalog.first?.isFavorite,true);XCTAssertEqual(model.catalog.first?.rating,5);XCTAssertEqual(model.catalog.first?.ratingsCount,1)}
 func testHomeResynchronizesFavoritesAndRatingAfterReturningFromDetail()async{let mix=sampleMix();let library=LibrarySpy();let model=HomeViewModel(content:CatalogSpy(snapshot:.init(mixes:[mix],articles:[])),library:library);await model.appear();library.favoriteMixIDs.insert(mix.id);library.ratings[mix.id]=4;model.syncLibraryState();XCTAssertEqual(model.mixes.first?.isFavorite,true);XCTAssertEqual(model.mixes.first?.personalRating,4);XCTAssertEqual(model.mixes.first?.rating,4);XCTAssertEqual(model.mixes.first?.ratingsCount,1)}
 func testArticlesLoadDetailFailureAndProtectedBookmark()async throws{let article=try JSONDecoder().decode(ArticleDTO.self,from:Data(#"{"id":"50000000-0000-0000-0000-000000000001","slug":"guide","title":"Guide","summary":"Summary","category":"fundamentals","readingMinutes":3}"#.utf8));let content=CatalogSpy(snapshot:.init(mixes:[],articles:[article]));let library=LibrarySpy();let list=ArticlesViewModel(content:content,library:library);await list.appear();XCTAssertEqual(list.articles.count,1);list.toggleBookmark(article);await Task.yield();XCTAssertEqual(library.authorized,[.bookmark]);let detail=ArticleDetailViewModel(article:article,content:content,library:library);content.detailError=true;await detail.appear();XCTAssertTrue(detail.failed)}
 func testBookmarkCollectionIsLiveAndReaderPublishesRollbackError()async throws{let article=try JSONDecoder().decode(ArticleDTO.self,from:Data(#"{"id":"50000000-0000-0000-0000-000000000001","slug":"guide","title":"Guide","summary":"Summary","category":"fundamentals","readingMinutes":3}"#.utf8));let content=CatalogSpy(snapshot:.init(mixes:[],articles:[article]));let library=LibrarySpy();let list=ArticlesViewModel(content:content,library:library);await list.appear();list.toggleBookmark(article);for _ in 0..<20 where list.bookmarks.isEmpty{await Task.yield()};XCTAssertEqual(list.bookmarks.map(\.slug),["guide"]);list.toggleBookmark(article);for _ in 0..<20 where !list.bookmarks.isEmpty{await Task.yield()};XCTAssertTrue(list.bookmarks.isEmpty);library.shouldFailBookmark=true;let detail=ArticleDetailViewModel(article:article,content:content,library:library);detail.toggleBookmark();for _ in 0..<20 where detail.errorMessage == nil{await Task.yield()};XCTAssertEqual(detail.errorMessage,L10n.Content.Error.network);XCTAssertFalse(detail.isBookmarked);detail.clearError();XCTAssertNil(detail.errorMessage)}
 private func sampleMix()->MixPreview{MixPreview(id:UUID(),title:"Mix",flavorTags:["Citrus"],flavorProfiles:[.citrus],sweetness:.subtle,acidity:.subtle,freshness:.subtle,ingredients:[],rating:nil,ratingsCount:0,strength:.medium,personalRating:nil,isFavorite:false,palette:.tropical)}
}
@MainActor private final class CatalogSpy:PublicCatalogServing{let snapshot:PublicCatalogSnapshot;var forces:[Bool]=[];var detailError=false;init(snapshot:PublicCatalogSnapshot){self.snapshot=snapshot};func catalog(locale:AppLocale,force:Bool)async->PublicCatalogSnapshot{forces.append(force);return snapshot};func articleDetail(_ id:String,locale:AppLocale)async throws->ArticleDetailDTO{if detailError{throw URLError(.badServerResponse)};fatalError()}}
@MainActor private final class LibrarySpy:AuthLibraryServing{var isAuthenticated=true;var favoriteMixIDs:Set<UUID>=[];var ratings:[UUID:Int]=[:];var bookmarkedArticleSlugs:Set<String>=[];var libraryError:String?;var authorized:[ProtectedAction]=[];var shouldFailBookmark=false;func authorize(_ action:ProtectedAction,resume:@escaping()->Void){authorized.append(action);resume()};func setFavorite(_ enabled:Bool,mixId:UUID)async{};func setRating(_ score:Int?,mixId:UUID)async{};func setArticleBookmark(_ enabled:Bool,slug:String)async{libraryError=nil;if shouldFailBookmark{libraryError=L10n.Content.Error.network;return};if enabled{bookmarkedArticleSlugs.insert(slug)}else{bookmarkedArticleSlugs.remove(slug)}}}
