import assert from "node:assert/strict";
import test from "node:test";
import {buildBlackburnSnapshot,diffBlackburnSnapshots,discoverBlackburnStore,inferBlackburn,renderBlackburnSnapshot,slugifyBlackburn} from "../src/blackburnRefresh.js";
import {loadBlackburnPages} from "../src/refreshBlackburn.js";
import {archiveMissingBlackburnProducts} from "../src/db/importCatalogSeed.js";

const meta={pageUrl:"https://www.blckburn.com/taste",apiUrl:"https://store.tildaapi.com/api/getproductslist/",recid:"596214532",storepartuid:"260605997971",accessedAt:"2026-09-10",verifiedAt:"2026-09-10",publisher:"BlackBurn" as const};
const raw=(uid:string,title:string,descr="Лимон")=>({uid,title,descr,text:descr,partuids:"[]",price:"999",img:"secret.jpg",quantity:4});

test("discovers one official store configuration and rejects ambiguity",()=>{const html='<div id="rec596214532"><script>"storepart":"260605997971"</script>';assert.deepEqual(discoverBlackburnStore(html),{recid:"596214532",storepartuid:"260605997971"});assert.throws(()=>discoverBlackburnStore(html+html.replaceAll("596214532","1").replaceAll("260605997971","2")),/found 2/)});
test("paginates to declared API total through an injected fetcher",async()=>{const calls:string[]=[];const fetcher=async(url:string)=>{calls.push(url);if(url.endsWith("/taste"))return new Response('<div id="rec596214532"><script>"storepart":"260605997971"</script>');const second=url.includes("slice=2");return new Response(JSON.stringify({total:3,products:second?[raw("3","C")]:[raw("1","A"),raw("2","B")],nextslice:second?null:2}),{headers:{"content-type":"application/json"}})};const result=await loadBlackburnPages(fetcher);assert.equal(result.pages.length,2);assert.match(calls[2]!,/slice=2/)});
test("snapshot is deterministic, collision-safe and drops commerce/media fields",()=>{const snapshot=buildBlackburnSnapshot([{total:2,products:[raw("1","Lemon"),raw("2","Orange")]}],meta);const used=new Set<string>();assert.notEqual(slugifyBlackburn("Same","1",used),slugifyBlackburn("Same","2",used));const text=renderBlackburnSnapshot(snapshot);for(const forbidden of ["price","quantity","secret.jpg"])assert(!text.includes(forbidden));assert.deepEqual(diffBlackburnSnapshots(snapshot,snapshot),{added:[],changed:[],removed:[],unclassified:[]});assert.equal(slugifyBlackburn("", "7"),"product-7")});
test("Iceberg is cooling evidence, never mint",()=>{const inferred=inferBlackburn("Iceberg Арктический лед, охлаждающий вкус");assert(inferred.tags.includes("cooling"));assert(!inferred.tags.includes("mint"));assert.equal(inferred.freshness,"pronounced")});
test("unclassified official products fail instead of receiving an invented tag",()=>{assert.throws(()=>buildBlackburnSnapshot([{total:1,products:[raw("1","Opaque","unknown evidence")]}],meta),/Unclassified/)});
test("archive query is scoped to BlackBurn and authoritative/legacy source URLs",async()=>{let captured="",values:unknown[]=[];const client={query:async(sql:string,args?:unknown[])=>{captured=sql;values=args??[];return{rowCount:2,rows:[]}}};assert.equal(await archiveMissingBlackburnProducts(client as never,[{lineSlug:"shock",productSlug:"lemon-shock"}]),2);assert.match(captured,/b\.slug='blackburn'/);assert.match(captured,/p\.status<>'archived'/);assert.deepEqual(values.slice(0,2),["https://www.blckburn.com/taste","https://hookahportal.ru/tobaccos/blackburn"])});
