import assert from "node:assert/strict";import test from "node:test";import {verifyProvenanceSources,type SourceInput} from "../src/provenanceVerifier.js";import type {SeedBrand} from "../seeds/catalog-v1.js";import type {OfficialMixSeed} from "../seeds/mixes-v1.js";
const source=(key:string,url="https://example.test/catalog",collection:SourceInput["collection"]="catalog"):SourceInput=>({key,url,collection,title:"Source",publisher:"Publisher",accessedAt:"2026-01-01",verifiedAt:"2026-01-01",confidence:"high",notes:"fixture"});
const brands:SeedBrand[]=[{slug:"musthave",name:"MUSTHAVE",sourceKey:"catalog",lines:[{slug:"original",name:"Original",strength:"medium",sourceKey:"catalog",products:[{slug:"berry",nameRu:"Ягоды",nameEn:"Berries",translationOrigin:"official",sourceKey:"catalog",tags:["berry"],sweetness:"pronounced",acidity:"subtle",freshness:"subtle"},{slug:"lemon",nameRu:"Лимон",nameEn:"Lemon",translationOrigin:"official",sourceKey:"catalog",tags:["citrus"],sweetness:"subtle",acidity:"pronounced",freshness:"subtle"}]}]}];
const mix:OfficialMixSeed={slug:"fixture",titleRu:"Микс",titleEn:"Mix",summaryRu:"Описание",summaryEn:"Summary",translationOrigin:"official",sourceKey:"musthave-mix-42",components:[{product:"musthave/original/berry",percentage:60},{product:"musthave/original/lemon",percentage:40}]};
const long=(value:string)=>`<html><body>${value} ${"editorial source content ".repeat(8)}</body></html>`;

test("verifier deduplicates URLs, maps every key and requests redirect follow with stable headers",async()=>{let calls=0;const fetcher:typeof fetch=async(_input,init)=>{calls++;assert.equal(init?.redirect,"follow");assert.match(new Headers(init?.headers).get("user-agent")??"",/HookahBoss-ProvenanceVerifier/);return new Response(long("catalog"),{status:200})};const report=await verifyProvenanceSources([source("a"),source("b")],[],[],{fetcher,retries:0,now:()=>new Date("2026-01-02T00:00:00Z")});assert.equal(calls,1);assert.deepEqual(report.results[0]?.keys,["a","b"]);assert.equal(report.results[0]?.semanticStatus,"reachability_only");assert.equal(report.generatedAt,"2026-01-02T00:00:00.000Z")});

test("verifier retries transient responses but not permanent responses",async()=>{let transientCalls=0;const retry:typeof fetch=async()=>new Response(long("ok"),{status:++transientCalls===1?503:200});const ok=await verifyProvenanceSources([source("a")],[],[],{fetcher:retry,retries:1});assert.equal(ok.results[0]?.attempts,2);assert.equal(ok.results[0]?.ok,true);let permanentCalls=0;const bad=await verifyProvenanceSources([source("b")],[],[],{fetcher:async()=>{permanentCalls++;return new Response("gone",{status:404})},retries:2});assert.equal(permanentCalls,1);assert.equal(bad.results[0]?.ok,false)});

test("verifier aborts timed out requests and retries only within the bound",async()=>{let calls=0;const hanging:typeof fetch=async(_input,init)=>{calls++;return await new Promise((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("timed out","AbortError")),{once:true}))};const report=await verifyProvenanceSources([source("slow")],[],[],{fetcher:hanging,timeoutMs:5,retries:1});assert.equal(calls,2);assert.equal(report.results[0]?.attempts,2);assert.equal(report.results[0]?.ok,false)});
test("reachability-only accepts a nontrivial dynamic HTML shell with a warning but rejects a tiny body",async()=>{const dynamic=`<html><script>${"hydration payload ".repeat(100)}</script><div>app</div></html>`,fetcher:typeof fetch=async input=>new Response(String(input).includes("dynamic")?dynamic:"<html>tiny</html>",{status:200});const report=await verifyProvenanceSources([source("dynamic","https://example.test/dynamic"),source("tiny","https://example.test/tiny")],[],[],{fetcher,retries:0});const accepted=report.results.find(r=>r.keys.includes("dynamic"))!,tiny=report.results.find(r=>r.keys.includes("tiny"))!;assert.equal(accepted.ok,true);assert.equal(accepted.semanticStatus,"reachability_only");assert.deepEqual(accepted.warnings,["dynamic_shell_visible_text_short"]);assert.deepEqual(accepted.errors,[]);assert.equal(tiny.ok,false);assert.deepEqual(tiny.errors,["body_too_short"])});
test("MUSTHAVE semantic pages never receive the dynamic-shell bypass",async()=>{const url="https://musthave.ru/showmixes/view/42/",body=`<html><script>${"payload ".repeat(200)}</script></html>`;const report=await verifyProvenanceSources([source("musthave-mix-42",url,"mix")],[mix],brands,{fetcher:async()=>new Response(body,{status:200}),retries:0});assert.equal(report.results[0]?.ok,false);assert.equal(report.results[0]?.semanticStatus,"mismatch");assert.deepEqual(report.results[0]?.errors,["body_too_short"])});

test("MUSTHAVE semantic verifier accepts header percentage sequence and ordered composition names",async()=>{const url="https://musthave.ru/showmixes/view/42/",html=long("#ID 42 display berry 60% display lemon 40% structure Состав Berries Lemon");const report=await verifyProvenanceSources([source("musthave-mix-42",url,"mix")],[mix],brands,{fetcher:async()=>new Response(html,{status:200}),retries:0});assert.equal(report.results[0]?.semanticStatus,"verified");assert.equal(report.results[0]?.ok,true)});
test("MUSTHAVE semantic verifier ignores a percentage in the recipe title",async()=>{const url="https://musthave.ru/showmixes/view/42/",html=long("#ID 42 Mix with 100% statistics display berry 60% display lemon 40% structure Состав Berries Lemon");const report=await verifyProvenanceSources([source("musthave-mix-42",url,"mix")],[mix],brands,{fetcher:async()=>new Response(html,{status:200}),retries:0});assert.equal(report.results[0]?.ok,true);assert.equal(report.results[0]?.semanticStatus,"verified")});

test("MUSTHAVE semantic verifier reports recipe evidence mismatch",async()=>{const url="https://musthave.ru/showmixes/view/42/",html=long("#ID 41 berry 50% lemon 50% structure Состав Berries Lemon");const report=await verifyProvenanceSources([source("musthave-mix-42",url,"mix")],[mix],brands,{fetcher:async()=>new Response(html,{status:200}),retries:0});assert.equal(report.results[0]?.semanticStatus,"mismatch");assert.equal(report.results[0]?.ok,false);assert.ok(report.results[0]!.errors.some(error=>error.includes("#ID 42")))});
test("MUSTHAVE semantic verifier rejects swapped percentages or component order",async()=>{const url="https://musthave.ru/showmixes/view/42/";for(const evidence of ["#ID 42 berry 40% lemon 60% structure Состав Berries Lemon","#ID 42 berry 60% lemon 40% structure Состав Lemon Berries"]){const report=await verifyProvenanceSources([source("musthave-mix-42",url,"mix")],[mix],brands,{fetcher:async()=>new Response(long(evidence),{status:200}),retries:0});assert.equal(report.results[0]?.ok,false);assert.equal(report.results[0]?.semanticStatus,"mismatch")}});
test("MUSTHAVE v3 source key maps to its seeded recipe rather than a derived key",async()=>{const url="https://musthave.ru/showmixes/view/42/",v3={...mix,sourceKey:"musthave-mix-v3-42"};const report=await verifyProvenanceSources([source("musthave-mix-v3-42",url,"mix")],[v3],brands,{fetcher:async()=>new Response(long("#ID 42 berry 60% lemon 40% structure Состав Berries Lemon"),{status:200}),retries:0});assert.equal(report.results[0]?.ok,true);assert.equal(report.results[0]?.semanticStatus,"verified")});
