import type { Intensity } from "../seeds/catalog-v1.js";

export type BlackburnProduct={uid:string;slug:string;title:string;descriptionRu:string;summaryRu:string;family:"Original"|"Shock"|"Something"|"KMTM";tags:string[];sweetness:Intensity;acidity:Intensity;freshness:Intensity};
export type BlackburnSnapshot={source:{pageUrl:string;apiUrl:string;recid:string;storepartuid:string;accessedAt:string;verifiedAt:string;publisher:"BlackBurn"};products:BlackburnProduct[]};
type Raw={uid?:unknown;title?:unknown;descr?:unknown;text?:unknown;partuids?:unknown};type Page={total?:unknown;products?:unknown;slice?:unknown;nextslice?:unknown;filters?:unknown};
const families=new Map([["669935161871","Shock"],["632179160481","Something"],["476174242871","KMTM"]] as const);
export function discoverBlackburnStore(html:string):{recid:string;storepartuid:string}{const recids=[...html.matchAll(/id=["']rec(\d+)["'][^>]*[\s\S]{0,20000}?storepart["']?\s*:\s*["'](\d+)["']/gi)].map(m=>[m[1]!,m[2]!] as const),unique=[...new Map(recids.map(v=>[v.join(":"),v])).values()];if(unique.length!==1)throw new Error(`Expected one BlackBurn store configuration, found ${unique.length}`);return{recid:unique[0]![0],storepartuid:unique[0]![1]}}
const rules:[string,RegExp][]=[
 ["cooling",/арктич|охлажд|замораж|холод|л[её]д|\bice(?:berg)?\b|freez|cooling/],
 ["lemon",/лимон|lemon/],["orange",/апельсин|мандарин|orange|mirinda/],["grapefruit",/грейпфрут|grapefruit|помело|pomelo/],["citrus",/цитрус/],["apple",/яблок|apple/],["pineapple",/ананас|pineapple|ananas/],["peach",/персик|peach/],["raspberry",/малин|raspber/],["strawberry",/клубник|strawber/],["blackberry",/ежевик|blackber/],["blackcurrant",/черн(?:ая|ой) смородин|blackcurrant|currant shock/],["cranberry",/клюкв|cranber/],["berry",/ягод|berry|смородин|брусник/],["cherry",/вишн|cherry/],["grape",/виноград|grape/],["watermelon",/арбуз|watermelon/],["banana",/банан/],["passion-fruit",/маракуй|passion|real p\.f/],["lychee",/личи|lychee/],["feijoa",/фейхоа|feijoa/],["papaya",/папай|papaya/],["tropical-fruit",/тропич|манго|mango|lulo|луло|салак|salak|tropic|экзот/],["mint",/мят|mint|tik tak|after 8/],["basil",/базилик|basil/],["herbal",/чай|tea|трав/],["coconut",/кокос|coconut|malibu/],["cream",/слив|cream|чизкейк|cheesecake|пудинг|pudding|брюле|brûlée/],["yoghurt",/йогурт|yogurt/],["ice-cream",/морожен|icecream|ice snow/],["cacao",/шоколад|brownie|nutella/],["pastry",/брауни|brownie|чизкейк|cheesecake|выпеч|десерт|muesli|мюсли/],["honey",/м[её]д|honey/],["candy",/конфет|леден|bubblegum|skittles|haribon|halls|sweets/],["cola",/кола|cola/],["beverage",/лимонад|lemonade|сода|soda|energy|smoothie|коктейл|pinacolada|пинаколада/],["fir",/ёлк|елк|ёlka/],["pomegranate",/гранат|garnet/],["cucumber",/огур/],["spices",/прян|спец|cinnamon|кориц|irish/],["elderberry",/бузин|elderberry/]
];
export function slugifyBlackburn(title:string,uid:string,used:Set<string>=new Set()):string{const base=title.normalize("NFKD").replace(/[Ёё]/g,"yo").replace(/[А-Яа-я]/g,char=>({а:"a",б:"b",в:"v",г:"g",д:"d",е:"e",ж:"zh",з:"z",и:"i",й:"y",к:"k",л:"l",м:"m",н:"n",о:"o",п:"p",р:"r",с:"s",т:"t",у:"u",ф:"f",х:"h",ц:"c",ч:"ch",ш:"sh",щ:"sch",ъ:"",ы:"y",ь:"",э:"e",ю:"yu",я:"ya"} as Record<string,string>)[char.toLowerCase()]??"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-|-$/g,"").toLowerCase()||`product-${uid}`;let slug=base;if(used.has(slug))slug=`${base}-${uid}`;used.add(slug);return slug}
export function inferBlackburn(text:string):Pick<BlackburnProduct,"tags"|"sweetness"|"acidity"|"freshness">{const normalized=text.normalize("NFKC").toLowerCase(),tags=rules.filter(([,regex])=>regex.test(normalized)).map(([tag])=>tag);return{tags:[...new Set(tags)],sweetness:/слад|конфет|десерт|крем|слив|шоколад|м[её]д|sweet|candy|cream|brownie|pudding/.test(normalized)?"pronounced":"subtle",acidity:/кисл|цитрус|лимон|лайм|грейпфрут|cranber|currant|lemon|grapefruit/.test(normalized)?"pronounced":"subtle",freshness:/свеж|холод|л[её]д|мят|ice|mint|halls/.test(normalized)?"pronounced":"subtle"}}
export function normalizeOfficialText(value:unknown):string{if(typeof value!=="string")return"";return value.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&quot;|&#34;/gi,'"').replace(/&amp;|&#38;/gi,"&").replace(/\r/g,"").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").replace(/[ \t]{2,}/g," ").trim()}
function parseParts(value:unknown):string[]{if(Array.isArray(value))return value.map(String);if(typeof value==="string")try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}return[]}
export function buildBlackburnSnapshot(pages:Page[],meta:BlackburnSnapshot["source"]):BlackburnSnapshot{const declared=new Set(pages.map(p=>p.total));if(declared.size!==1||![...declared][0]||!Number.isInteger([...declared][0]))throw new Error("Invalid or inconsistent BlackBurn total");const total=Number([...declared][0]),raw=pages.flatMap(p=>Array.isArray(p.products)?p.products as Raw[]:[]);if(raw.length!==total)throw new Error(`Expected ${total} products, received ${raw.length}`);const ids=new Set<string>(),titles=new Set<string>(),used=new Set<string>(),unclassified:string[]=[];const products=raw.map(item=>{const uid=String(item.uid??"").trim(),title=normalizeOfficialText(item.title),descriptionRu=normalizeOfficialText(item.text),summaryRu=normalizeOfficialText(item.descr);if(!uid||!title||(!descriptionRu&&!summaryRu))throw new Error("BlackBurn product missing uid/title/description evidence");if(ids.has(uid)||titles.has(title.toLowerCase()))throw new Error(`Duplicate BlackBurn product ${uid}/${title}`);ids.add(uid);titles.add(title.toLowerCase());const resolvedDescription=descriptionRu||summaryRu,resolvedSummary=summaryRu||descriptionRu;const evidence=inferBlackburn(`${title} ${resolvedSummary} ${resolvedDescription}`);if(!evidence.tags.length)unclassified.push(title);const family=parseParts(item.partuids).map(id=>families.get(id as never)).find(Boolean)??"Original";return{uid,slug:slugifyBlackburn(title,uid,used),title,descriptionRu:resolvedDescription,summaryRu:resolvedSummary,family,...evidence} as BlackburnProduct});if(unclassified.length)throw new Error(`Unclassified BlackBurn products: ${unclassified.join(", ")}`);return{source:meta,products:products.sort((a,b)=>a.title.localeCompare(b.title,"en"))}}
export function renderBlackburnSnapshot(snapshot:BlackburnSnapshot):string{return `// Generated by npm run catalog:refresh:blackburn. Commerce/media fields intentionally excluded.\nimport type { BlackburnSnapshot } from "../src/blackburnRefresh.js";\nexport const blackburnSnapshot:BlackburnSnapshot=${JSON.stringify(snapshot,null,2)};\n`}
export function diffBlackburnSnapshots(before:BlackburnSnapshot|undefined,after:BlackburnSnapshot){const previous=new Map((before?.products??[]).map(p=>[p.uid,p])),next=new Map(after.products.map(p=>[p.uid,p]));return{added:[...next.keys()].filter(id=>!previous.has(id)),changed:[...next].filter(([id,p])=>previous.has(id)&&JSON.stringify(previous.get(id))!==JSON.stringify(p)).map(([id])=>id),removed:[...previous.keys()].filter(id=>!next.has(id)),unclassified:[] as string[]}}
