import type { CatalogSource } from "../seeds/catalog-v1.js";
import type { OfficialMixSeed } from "../seeds/mixes-v1.js";
import type { SeedBrand } from "../seeds/catalog-v1.js";

export type SourceCollection="catalog"|"mix"|"article";
export type SourceInput=CatalogSource&{collection:SourceCollection};
export type VerificationResult={url:string;keys:string[];collections:SourceCollection[];ok:boolean;httpStatus?:number;attempts:number;finalUrl?:string;semanticStatus:"verified"|"reachability_only"|"mismatch"|"not_reached";errors:string[];warnings?:string[]};
export type VerificationReport={generatedAt:string;summary:{sourceKeys:number;uniqueUrls:number;passed:number;failed:number;semanticVerified:number;reachabilityOnly:number};results:VerificationResult[]};
export type VerifyOptions={fetcher?:typeof fetch;concurrency?:number;timeoutMs?:number;retries?:number;now?:()=>Date;userAgent?:string};

const transient=new Set([408,425,429,500,502,503,504]);
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function textFromHTML(html:string):string{return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(x[0-9a-f]+|\d+);/gi,(_,raw:string)=>{const n=raw[0]?.toLowerCase()==="x"?parseInt(raw.slice(1),16):parseInt(raw,10);return Number.isFinite(n)?String.fromCodePoint(n):" "}).normalize("NFKC").replace(/\s+/g," ").trim()}
const normalized=(value:string)=>value.normalize("NFKC").toLocaleLowerCase("ru").replace(/[’‘`]/g,"'").replace(/\s+/g," ").trim();

function productNames(brands:SeedBrand[]):Map<string,string[]>{const result=new Map<string,string[]>();for(const brand of brands)for(const line of brand.lines)for(const product of line.products)result.set(`${brand.slug}/${line.slug}/${product.slug}`,[product.nameRu,product.nameEn].filter((v,i,a)=>v&&a.indexOf(v)===i).map(normalized));return result}
function musthaveSemantic(url:string,sourceKeys:string[],body:string,mixes:OfficialMixSeed[],names:Map<string,string[]>):string[]{const match=url.match(/\/showmixes\/view\/(\d+)\/?(?:[?#]|$)/);if(!match)return[];const id=match[1]!,text=normalized(textFromHTML(body)),errors:string[]=[],idMatch=new RegExp(`#id\\s*${id}(?!\\d)`,"i").exec(text);if(!idMatch)errors.push(`missing #ID ${id}`);const recipe=mixes.find(m=>sourceKeys.includes(m.sourceKey));if(!recipe)return[`missing seeded recipe for ${sourceKeys.join(" or ")}`];const structureAt=text.indexOf(" structure ",idMatch?.index??0),compositionAt=structureAt>=0?structureAt:text.indexOf(" состав ",idMatch?.index??0);if(!idMatch||compositionAt<0){errors.push("missing recipe/composition boundary");return errors}const recipeSection=text.slice(idMatch.index,compositionAt),publishedPercentages=[...recipeSection.matchAll(/\b(\d{1,3})\s*%/g)].map(m=>Number(m[1])).slice(-recipe.components.length),expectedPercentages=recipe.components.map(c=>c.percentage);if(publishedPercentages.length!==expectedPercentages.length||publishedPercentages.some((value,index)=>value!==expectedPercentages[index]))errors.push(`percentage sequence mismatch: expected ${expectedPercentages.join(",")}, found ${publishedPercentages.join(",")}`);const composition=text.slice(compositionAt);let cursor=0;for(const component of recipe.components){const variants=names.get(component.product)??[],positions=variants.map(name=>composition.indexOf(name,cursor)).filter(position=>position>=0);if(!positions.length){errors.push(`missing/out-of-order component ${component.product}`);continue}cursor=Math.min(...positions)+1}return errors}

export async function verifyProvenanceSources(sources:SourceInput[],mixes:OfficialMixSeed[],brands:SeedBrand[],options:VerifyOptions={}):Promise<VerificationReport>{
 const fetcher=options.fetcher??fetch,concurrency=Math.max(1,Math.min(options.concurrency??5,12)),timeoutMs=options.timeoutMs??10_000,retries=options.retries??2,userAgent=options.userAgent??"HookahBoss-ProvenanceVerifier/1.0 (+source-audit; no-cookies)",names=productNames(brands);
 const grouped=new Map<string,SourceInput[]>();for(const source of sources)grouped.set(source.url,[...(grouped.get(source.url)??[]),source]);const groups=[...grouped.entries()],results=new Array<VerificationResult>(groups.length),worker=async(index:number)=>{for(let i=index;i<groups.length;i+=concurrency){const [url,entries]=groups[i]!,base={url,keys:entries.map(e=>e.key),collections:[...new Set(entries.map(e=>e.collection))]};let response:Response|undefined,error="",attempts=0;for(;attempts<=retries;attempts++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{response=await fetcher(url,{method:"GET",redirect:"follow",signal:controller.signal,headers:{"user-agent":userAgent,"accept":"text/html,application/xhtml+xml,text/plain;q=0.8,*/*;q=0.1"}});if(response.ok||!transient.has(response.status))break}catch(e){error=e instanceof Error?e.name:"network_error"}finally{clearTimeout(timer)}if(attempts<retries)await sleep(Math.min(100*2**attempts,500))}
   const attemptCount=Math.min(attempts+1,retries+1);if(!response?.ok){results[i]={...base,ok:false,httpStatus:response?.status,attempts:attemptCount,finalUrl:response?.url,semanticStatus:"not_reached",errors:[error||`HTTP ${response?.status??"network"}`]};continue}let body="";try{body=await response.text()}catch{results[i]={...base,ok:false,httpStatus:response.status,attempts:attemptCount,finalUrl:response.url,semanticStatus:"not_reached",errors:["response_body_unreadable"]};continue}const musthave=/musthave\.ru\/showmixes\/view\/\d+/.test(url),visibleLength=textFromHTML(body).length;if(visibleLength<100){if(!musthave&&body.length>=1024){results[i]={...base,ok:true,httpStatus:response.status,attempts:attemptCount,finalUrl:response.url,semanticStatus:"reachability_only",errors:[],warnings:["dynamic_shell_visible_text_short"]};continue}results[i]={...base,ok:false,httpStatus:response.status,attempts:attemptCount,finalUrl:response.url,semanticStatus:musthave?"mismatch":"reachability_only",errors:["body_too_short"]};continue}const semanticErrors=musthave?musthaveSemantic(url,base.keys,body,mixes,names):[];results[i]={...base,ok:semanticErrors.length===0,httpStatus:response.status,attempts:attemptCount,finalUrl:response.url,semanticStatus:musthave?(semanticErrors.length?"mismatch":"verified"):"reachability_only",errors:semanticErrors,warnings:[]}}
 };await Promise.all(Array.from({length:Math.min(concurrency,groups.length)},(_,i)=>worker(i)));const passed=results.filter(r=>r.ok).length;return{generatedAt:(options.now?.()??new Date()).toISOString(),summary:{sourceKeys:sources.length,uniqueUrls:groups.length,passed,failed:results.length-passed,semanticVerified:results.filter(r=>r.semanticStatus==="verified").length,reachabilityOnly:results.filter(r=>r.semanticStatus==="reachability_only"&&r.ok).length},results};
}
