import SwiftUI

struct AdminDashboardView:View {
 let client:APIClient
 var body:some View{NavigationStack{List(AdminResource.all){resource in NavigationLink{AdminResourceListView(client:client,resource:resource)}label:{AdminDashboardRow(client:client,resource:resource,icon:icon(resource.path))}.listRowBackground(AppTheme.card)}.listStyle(.plain).navigationTitle("admin.title").appScreenBackground()}}
 private func icon(_ path:String)->String{switch path{case "sources":"link";case "brands":"building.2";case "lines":"square.stack.3d.up";case "flavor-tags":"tag";case "products":"leaf";case "official-mixes":"square.grid.2x2";case "articles":"doc.text";default:"arrow.triangle.swap"}}
}

private struct AdminDashboardRow:View {
 let client:APIClient;let resource:AdminResource;let icon:String
 @State private var state:LoadState = .loading
 enum LoadState {case loading,count(Int),failed}
 var body:some View{HStack(spacing:12){Image(systemName:icon).foregroundStyle(AppTheme.gold).frame(width:30);VStack(alignment:.leading,spacing:3){Text(String(localized:String.LocalizationValue(resource.titleKey))).font(.body.weight(.medium));switch state{case .loading:Text("admin.dashboard.loading").foregroundStyle(.secondary);case .count(let count):Text(String(format:String(localized:"admin.dashboard.items"),count)).foregroundStyle(.secondary);case .failed:Text("admin.dashboard.unavailable").foregroundStyle(.secondary)}}.font(.caption);Spacer()}.contentShape(Rectangle()).task{do{state = .count(try await client.adminList(resource).count)}catch{state = .failed}}}
}

private struct AdminResourceListView:View {
 let client:APIClient;let resource:AdminResource
 @State private var records:[AdminRecord]=[];@State private var loading=true;@State private var error:String?;@State private var create=false
 var body:some View{List{if loading{ProgressView().frame(maxWidth:.infinity)}else if records.isEmpty{ContentUnavailableView("admin.empty",systemImage:"tray")}else{ForEach(records){record in NavigationLink{AdminEditorView(client:client,resource:resource,record:record){Task{await load()}}}label:{VStack(alignment:.leading){Text(record.title);Text(record.id).font(.caption2).foregroundStyle(.secondary)}}.swipeActions{Button(role:.destructive){Task{await remove(record)}}label:{Label("common.delete",systemImage:"trash")};if supportsStatus{Button{Task{await status("archived",record)}}label:{Label("admin.archive",systemImage:"archivebox")}.tint(.orange);Button{Task{await status("published",record)}}label:{Label("admin.publish",systemImage:"checkmark.seal")}.tint(.green)}}}}}.navigationTitle(String(localized:String.LocalizationValue(resource.titleKey))).appScreenBackground().toolbar{Button{create=true}label:{Image(systemName:"plus")}.accessibilityLabel("admin.create")}.task{await load()}.refreshable{await load()}.sheet(isPresented:$create){NavigationStack{AdminEditorView(client:client,resource:resource,record:nil){create=false;Task{await load()}}}}.alert("content.error.title",isPresented:Binding(get:{error != nil},set:{if !$0{error=nil}})){Button("common.close"){} }message:{Text(error ?? "")}}
 private var supportsStatus:Bool{resource.fields.contains{$0.key=="status"} && !["products","official-mixes"].contains(resource.path)}
 private func load()async{loading=true;do{records=try await client.adminList(resource);error=nil}catch{self.error=String(describing:error)};loading=false}
 private func status(_ value:String,_ record:AdminRecord)async{var body:[String:JSONValue]=["status":.string(value)];for key in ["sourceId","source_id","verifiedAt","verified_at"]{if let v=record.values[key]{body[key.contains("_") ? (key=="source_id" ? "sourceId":"verifiedAt"):key]=v}};do{_ = try await client.adminUpdate(resource,id:record.id,body:body);await load()}catch{self.error=String(describing:error)}}
 private func remove(_ record:AdminRecord)async{do{let body: [String:JSONValue]?=resource.path=="substitution-deny-rules" ? ["sourceProductId":record.values["sourceProductId"] ?? record.values["source_product_id"] ?? .null,"substituteProductId":record.values["substituteProductId"] ?? record.values["substitute_product_id"] ?? .null]:nil;try await client.adminDelete(resource,id:record.id,body:body);await load()}catch{self.error=String(describing:error)}}
}

private struct AdminEditorView:View {
 @Environment(\.dismiss)private var dismiss;let client:APIClient;let resource:AdminResource;let record:AdminRecord?;let onSaved:()->Void
 @State private var values:[String:String];@State private var saving=false;@State private var error:String?
 @State private var components:[AdminComponentRow];@State private var tags:[AdminTagRow];@State private var sections:[AdminArticleSectionRow]
 init(client:APIClient,resource:AdminResource,record:AdminRecord?,onSaved:@escaping ()->Void){self.client=client;self.resource=resource;self.record=record;self.onSaved=onSaved;var initial:[String:String]=[:];for field in resource.fields where field.kind != .json{initial[field.key]=record?.values[field.key]?.display ?? record?.values[Self.snake(field.key)]?.display ?? ""};if resource.fields.contains(where:{$0.key=="status"}),initial["status"]?.isEmpty != false{initial["status"]="draft"};_values=State(initialValue:initial);_components=State(initialValue:Self.componentRows(record));_tags=State(initialValue:Self.tagRows(record));_sections=State(initialValue:Self.sectionRows(record))}
 var body:some View{Form{ForEach(resource.fields.filter{$0.kind != .json}){field in if field.kind == .status{Picker(LocalizedStringKey(field.title),selection:binding(field.key)){Text("admin.status.draft").tag("draft");Text("admin.status.published").tag("published");Text("admin.status.archived").tag("archived")}}else{TextField(LocalizedStringKey(field.title),text:binding(field.key)).textInputAutocapitalization(.never).keyboardType(field.kind == .number ? .numberPad:.default)}};if resource.path=="official-mixes"{componentEditor};if resource.path=="products"{tagEditor};if resource.path=="articles"{articleEditor};if let error{Section{Text(error).foregroundStyle(.red)}}}.navigationTitle(record == nil ? "admin.create":"admin.edit").appScreenBackground().toolbar{ToolbarItem(placement:.cancellationAction){Button("common.cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("common.save"){Task{await save()}}.disabled(saving || (resource.path=="official-mixes" && AdminAggregateMapper.percentageTotal(components) != 100))};ToolbarItem(placement:.secondaryAction){EditButton()}}}
 private var componentEditor:some View{Section{ForEach($components){$row in HStack{AdminReferenceButton(client:client,resource:AdminResource.all.first{$0.path=="products"}!,selection:$row.productId,label:$row.productName);TextField("%",text:$row.percentage).keyboardType(.numberPad).frame(width:48);Text("%").foregroundStyle(.secondary)}.swipeActions{Button(role:.destructive){components.removeAll{$0.id==row.id}}label:{Image(systemName:"trash")}}}.onMove{components.move(fromOffsets:$0,toOffset:$1)};Button("admin.addComponent",systemImage:"plus"){components.append(.init())}}header:{HStack{Text("admin.components");Spacer();Text("\(AdminAggregateMapper.percentageTotal(components))%").foregroundStyle(AdminAggregateMapper.percentageTotal(components)==100 ? .green:.red).fontWeight(.semibold)}}}
 private var tagEditor:some View{Section("admin.tags"){ForEach($tags){$row in HStack{AdminReferenceButton(client:client,resource:AdminResource.all.first{$0.path=="flavor-tags"}!,selection:$row.tagId,label:$row.tagName);Stepper("\(row.weight)",value:Binding(get:{Int(row.weight) ?? 1},set:{row.weight=String($0)}),in:1...5).fixedSize()}.swipeActions{Button(role:.destructive){tags.removeAll{$0.id==row.id}}label:{Image(systemName:"trash")}}};Button("admin.addTag",systemImage:"plus"){tags.append(.init())}}}
 private var articleEditor:some View{Section("admin.sections"){ForEach($sections){$row in VStack(alignment:.leading,spacing:8){TextField("admin.section.headingRu",text:$row.headingRu);TextField("admin.section.bodyRu",text:$row.bodyRu,axis:.vertical).lineLimit(2...6);Divider();TextField("admin.section.headingEn",text:$row.headingEn);TextField("admin.section.bodyEn",text:$row.bodyEn,axis:.vertical).lineLimit(2...6)}.padding(.vertical,5).swipeActions{Button(role:.destructive){sections.removeAll{$0.id==row.id}}label:{Image(systemName:"trash")}}}.onMove{sections.move(fromOffsets:$0,toOffset:$1)};Button("admin.addSection",systemImage:"plus"){sections.append(.init())}}}
 private func binding(_ key:String)->Binding<String>{Binding(get:{values[key] ?? ""},set:{values[key]=$0})}
 private func save()async{saving=true;defer{saving=false};do{var prepared=values;if resource.path=="official-mixes"{prepared["components"]=try AdminAggregateMapper.components(components).display}else if resource.path=="products"{prepared["tags"]=try AdminAggregateMapper.tags(tags).display}else if resource.path=="articles"{let mapped=try AdminAggregateMapper.articleSections(sections);prepared["bodyRuStructured"]=mapped.ru.display;prepared["bodyEnStructured"]=mapped.en.display};let body=try AdminFormValidator.body(resource:resource,values:prepared);if let record{_ = try await client.adminUpdate(resource,id:record.id,body:body)}else{_ = try await client.adminCreate(resource,body:body)};onSaved();dismiss()}catch{self.error=error.localizedDescription}}
 private static func snake(_ input:String)->String{input.reduce(""){result,char in char.isUppercase ? result+"_"+char.lowercased():result+String(char)}}
 private static func value(_ record:AdminRecord?,_ key:String)->JSONValue?{record?.values[key] ?? record?.values[snake(key)]}
 private static func componentRows(_ record:AdminRecord?)->[AdminComponentRow]{guard case .array(let values)=value(record,"components")else{return []};return values.compactMap{guard case .object(let o)=$0 else{return nil};return .init(productId:o["productId"]?.display ?? o["product_id"]?.display ?? "",percentage:o["percentage"]?.display ?? "")}}
 private static func tagRows(_ record:AdminRecord?)->[AdminTagRow]{guard case .array(let values)=value(record,"tags")else{return []};return values.compactMap{guard case .object(let o)=$0 else{return nil};return .init(tagId:o["tagId"]?.display ?? o["tag_id"]?.display ?? "",weight:o["weight"]?.display ?? "1")}}
 private static func sectionRows(_ record:AdminRecord?)->[AdminArticleSectionRow]{func parts(_ key:String)->[(String,String)]{guard case .array(let values)=value(record,key)else{return []};return values.compactMap{guard case .object(let o)=$0 else{return nil};return(o["heading"]?.display ?? "",o["body"]?.display ?? "")}};let ru=parts("bodyRuStructured"),en=parts("bodyEnStructured"),count=max(ru.count,en.count);return(0..<count).map{.init(headingRu:$0<ru.count ? ru[$0].0:"",bodyRu:$0<ru.count ? ru[$0].1:"",headingEn:$0<en.count ? en[$0].0:"",bodyEn:$0<en.count ? en[$0].1:"")}}
}

private struct AdminReferenceButton:View {
 let client:APIClient;let resource:AdminResource;@Binding var selection:String;@Binding var label:String;@State private var show=false
 var body:some View{Button{show=true}label:{HStack{Text(label.isEmpty ? String(localized:"admin.choose"):label).lineLimit(2);Spacer();Image(systemName:"chevron.up.chevron.down")}}.sheet(isPresented:$show){AdminReferencePicker(client:client,resource:resource){record in selection=record.id;label=record.title;show=false}}}
}
private struct AdminReferencePicker:View {
 @Environment(\.dismiss)private var dismiss;let client:APIClient;let resource:AdminResource;let select:(AdminRecord)->Void;@State private var records:[AdminRecord]=[];@State private var search=""
 var body:some View{NavigationStack{List(records.filter{search.isEmpty||$0.title.localizedCaseInsensitiveContains(search)}){record in Button{select(record)}label:{VStack(alignment:.leading){Text(record.title);Text(record.id).font(.caption2).foregroundStyle(.secondary)}}}.searchable(text:$search).navigationTitle(String(localized:String.LocalizationValue(resource.titleKey))).appScreenBackground().toolbar{Button("common.cancel"){dismiss()}}.task{records=(try? await client.adminList(resource)) ?? []}}}
}
