// Generated by npm run catalog:refresh:blackburn. Commerce/media fields intentionally excluded.
import type { BlackburnSnapshot } from "../src/blackburnRefresh.js";
export const blackburnSnapshot:BlackburnSnapshot={
  "source": {
    "pageUrl": "https://www.blckburn.com/taste",
    "apiUrl": "https://store.tildaapi.com/api/getproductslist/?storepartuid=260605997971&recid=383378780",
    "recid": "383378780",
    "storepartuid": "260605997971",
    "accessedAt": "2026-09-10",
    "verifiedAt": "2026-09-10",
    "publisher": "BlackBurn"
  },
  "products": [
    {
      "uid": "926420251041",
      "slug": "after-8",
      "title": "After 8",
      "descriptionRu": "Вкус шоколадных конфет с мятой. Отлично дополняет любой вкус BlackBurn, так как сразу обладает и умеренной сладостью и свежестью. Мята создает первое ощущение свежести, но после выдыхания вы почувствуете сладкое послевкусие шоколада.",
      "summaryRu": "Вкус шоколадных конфет с мятой.",
      "family": "Original",
      "tags": [
        "mint",
        "cacao",
        "candy",
        "cola"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "169059845241",
      "slug": "almond-icecream",
      "title": "Almond Icecream",
      "descriptionRu": "Потрясающий вкус миндального мороженого. Горьковато-терпкий аромат свежего миндаля в сочетании с освежающей сливочно-молочной сладостью. Насыщенный, нежный и пикантный бленд, который дает много дыма и долго курится.",
      "summaryRu": "Миндальное мороженое",
      "family": "Original",
      "tags": [
        "cream",
        "ice-cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "654286781751",
      "slug": "ananas-shock",
      "title": "Ananas Shock",
      "descriptionRu": "Восхитительный и натуральный вкус кислого ананаса в табаке BlackBurn - Ananas Shock. Насладитесь ярко выраженной тропической кислинкой сочного фрукта, которая аж пощипывает язык! В интересном и богатом букете можно уловить легкую сладость и мягкие цветочные ноты. Остается приятное послевкусие. Продукт отлично курится соло. А если вы соскучились по тропикам, то сделайте крутой экзотический микс - смешайте с мятой и кокосом.",
      "summaryRu": "Кислый ананас",
      "family": "Shock",
      "tags": [
        "pineapple",
        "tropical-fruit",
        "mint",
        "coconut"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "635357533551",
      "slug": "apple-shock",
      "title": "Apple Shock",
      "descriptionRu": "Давно ищете идеальное яблоко, Возможно вы найдете его в табаке Apple Shock от BlackBurn. Это настоящее кислое зеленое яблоко и ничего лишнего. Аромат получился очень яркий, насыщеннный и \"сочный\". В сочетание с хорошей крепостью этот табак может занять почетное место среди ваших любимых вкусов. Советуем!",
      "summaryRu": "Кислое яблоко",
      "family": "Shock",
      "tags": [
        "apple"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "197679894031",
      "slug": "asian-lychee",
      "title": "Asian Lychee",
      "descriptionRu": "Абсолютно необычный и вместе с тем интересный вкус экзотического личи. Сладкий фруктовый аромат не оставит равнодушным, а его яркое послевкусие поможет окунуться в атмосферу тропического отдыха, что разнообразит и скрасит любой вечер.",
      "summaryRu": "Азиатский личи",
      "family": "Original",
      "tags": [
        "lychee",
        "tropical-fruit"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "386466577561",
      "slug": "barberry-shock",
      "title": "Barberry Shock",
      "descriptionRu": "Мы привыкли, что если заявлен барбарис, то чаще всего это оказываются сладкие конфетки, не в этот раз. Barberry Shock изменяет привычное положение дел и дарит очень кислый аромат. Вкус невероятно яркий, а забитый в соло сводит скулы даже самым ярым фанатам кислых вкусов.",
      "summaryRu": "Кислый барбарис",
      "family": "Shock",
      "tags": [
        "berry",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "734969227151",
      "slug": "basilic",
      "title": "Basilic",
      "descriptionRu": "Насыщенно-душистый, слегка вяжущий аромат свежего зеленого базилика. Сделает даже самые обычные миксы изысканными.",
      "summaryRu": "Базилик",
      "family": "Shock",
      "tags": [
        "basil"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "319703031901",
      "slug": "berry-lemonade",
      "title": "Berry Lemonade",
      "descriptionRu": "Ледяная прохлада, свежесть мяты и сумасшедшая смесь сладости и кислинки любимых спелых ягод — ингредиенты, которые делают ягодный лимонад одним из главных сезонных напитков. BlackBurn Berry Lemonade стирает рамки сезонности и передает всю палитру вкуса в любимом для тебя формате в любое время года!",
      "summaryRu": "Ягодный лимонад",
      "family": "Shock",
      "tags": [
        "cooling",
        "lemon",
        "berry",
        "mint",
        "beverage"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "997059712301",
      "slug": "black-honey",
      "title": "Black Honey",
      "descriptionRu": "Насыщенный вкус меда с оттенками полевых цветов.\nНасыщенный крепкий вкус меда и полевых цветов. Лучшего табака со вкусом меда вы не попробуете, глубокий аромат луговых цветов в сочетании с тягуче-сладким медом, отлично курится в холодное время года.",
      "summaryRu": "Цветочный мед",
      "family": "Original",
      "tags": [
        "cooling",
        "honey"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "185127490081",
      "slug": "blackberry-lemonade",
      "title": "Blackberry Lemonade",
      "descriptionRu": "Плотный и насыщенный. Тот самый, о котором ты мечтаешь в знойный летний день и в холодный зимний вечер. Сочный, словно спелая, только что сорванная с куста ежевика. Секунду назад она попала в блендер и превратилась в потрясающий напиток с небольшой пенкой и ярким кисло-сладким ароматом. Переродилась из ягод в лимонад — теперь он прямо перед тобой, в баночке. Твой Blackberry Lemonade от BlackBurn!",
      "summaryRu": "Ежевичный лимонад",
      "family": "Original",
      "tags": [
        "cooling",
        "lemon",
        "blackberry",
        "berry",
        "beverage"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "363609907231",
      "slug": "blackburn-feat-guf-ice-baby",
      "title": "BLACKBURN feat. GUF - ICE BABY",
      "descriptionRu": "Первый в истории кальянной индустрии коллаборационный вкус с артистом\n\nЯгодный сорбет со свежим грейпфрутом\n\nЯркий вкус лесных ягод, чарующий аромат грейпфрута создадут легкое летнее настроение, а прохлада приятно расслабит после тяжелого дня. В меру сладкий, в меру кислый, в меру свежий.\n\nПриятная сладость на вдохе и легкая кислинка на выдохе.\n\nЕсли вы устали от приторных вкусов и хочется чего нибудь натурального и не напрягающего, то вам подойдет ICE BABY.\n\nНасыщенный и сбалансированный вкус прекрасно раскрывается в соло.\n\nВкус положен на табачную основу темного листа Burley. Средняя нарезка, оптимальная сиропность. Не боится перегрева и быстро восстанавливается. Благодаря высокотемпературной обработке табак приобретает мягкий сбалансированный вкус.",
      "summaryRu": "Ягодный сорбет с грейпфрутом",
      "family": "Original",
      "tags": [
        "cooling",
        "grapefruit",
        "berry"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "559161634342",
      "slug": "blackcola",
      "title": "Blackcola",
      "descriptionRu": "Непревзойденная классика в исполнении BLACKBURN\nКола, какой она должны быть. Желанная, утоляющая жажду рецепторов, позволяющая почувствовать фееричность вкуса и ощутить легкую щекотку от пузырьков. Идеальная гармония сладости, приятной кислинки с почти незаметными нотками цитруса.",
      "summaryRu": "Кола",
      "family": "Original",
      "tags": [
        "citrus",
        "cola"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "846615489591",
      "slug": "brownie",
      "title": "Brownie",
      "descriptionRu": "Когда десерт не содержит никаких лишних калорий, только безупречный вкус нежного шоколадного бисквита. Нотки любимого лакомства с легкой горчинкой и аппетитными сладкими полутонами принесут много дымного удовольствия.",
      "summaryRu": "Шоколадный десерт",
      "family": "Original",
      "tags": [
        "cacao",
        "pastry",
        "cola"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "182543698752",
      "slug": "bubblegum",
      "title": "Bubblegum",
      "descriptionRu": "Яркий взрыв вкуса фруктовой жвачки\n\nВкус раскрывается свежим и ярким ароматом любимой жвачки с медовой дыней, аппетитной кислинкой и сладостью фруктов. BLACKBURN Bubblegum — это воплощение сладости и ностальгии, погружающее в забвенные времена. Этот вкус как первый поцелуй, который остается в памяти на всю жизнь — мягкий и столь же выразительный.",
      "summaryRu": "Фруктовая жвачка",
      "family": "Original",
      "tags": [
        "mint",
        "honey",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "964263927411",
      "slug": "cane-mint",
      "title": "Cane Mint",
      "descriptionRu": "Классический вкус для табака, но этот факт не преуменьшает его плюсов. Неудивительно, что многие предпочитают именно его, ведь мята прекрасно освежает и тонизирует, помогает расслабиться в конце тяжелого дня. Вы сможете насладиться и легкой сладостью аромата, скользящей на фоне освежающей мяты.",
      "summaryRu": "Тростниковая мята",
      "family": "Original",
      "tags": [
        "mint"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "907045010081",
      "slug": "cheesecake",
      "title": "Cheesecake",
      "descriptionRu": "Незаменимый десерт любой кофейни и ресторана. Нежный сливочно-сырный вкус, который идеально подчёркивается сбалансированной сладостью песочного печенья. Чизкейк от BlackBurn — тот самый случай, когда можно поддаться искушению: нежнейший десерт и никаких калорий даже после шести! Это вкусно и без лишних точек.",
      "summaryRu": "Чизкейк",
      "family": "Original",
      "tags": [
        "herbal",
        "cream",
        "pastry"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "397293196811",
      "slug": "cherry-garden",
      "title": "Cherry Garden",
      "descriptionRu": "В этом вкусе прячется очень натуральная спелая вишня, и если вы ищете идеальный вишневый вкус, возможно, это он! Кисло-сладкая, с терпкими нотами, именно такой должна быть идеальная вишня на наш взгляд. В сочетание с хорошей крепостью у Cherry Garden есть все шансы занять почетное место в вашем топе вкусов.",
      "summaryRu": "Черешневый сок",
      "family": "Original",
      "tags": [
        "cherry"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "340023837291",
      "slug": "cherry-shock",
      "title": "Cherry Shock",
      "descriptionRu": "Насыщенный вкус кислой вишни, терпкий и ароматный. Если вы в поисках аромата вишни, приближенного к натуральному, Cherry Shock может идеально вам подойти. Отличная кислая вишня с хорошей крепостью табака BlackBurn однозначно заслуживает вашего внимания и вполне вероятно может стать вашим фаворитом среди ягодных вкусов.",
      "summaryRu": "Кислая вишня",
      "family": "Shock",
      "tags": [
        "berry",
        "cherry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "831461736181",
      "slug": "chupa-graper",
      "title": "Chupa Graper",
      "descriptionRu": "Вот эта газировка BlackBurn точно утолит любую жажду. Виноградный вкус довольно сложный для передачи, поэтому от него частенько ждешь подвоха. Но эта газировка приятно удивляет.\n\nАромат «живой», как будто натуральный фрукт. По вкусу напоминает виноградный сок, насыщенный, где-то даже терпковатый, а на фоне раскрывается вроде как что-то медово-спрайтовое. В соло заходит «на ура».\n\nВкус отлично чувствуется, щедро вместе с дымом сопровождает весь процесс. Весь час не возникает сомнений, что в чаше неприторный, но сладко-терпкий виноградный сок.\n\nСмесь показывает себя жаростойкой, в случае перегрева восстанавливается сравнительно быстро, а по крепости выше средней. Вообще сочный и, наверное, один из самых долгоиграющих вкусов.",
      "summaryRu": "Виноградный чупа чупс",
      "family": "KMTM",
      "tags": [
        "grape",
        "honey"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "180317021431",
      "slug": "cranberry-shock",
      "title": "Cranberry Shock",
      "descriptionRu": "Шоковая терапия от Burn продолжается до безумия кислой клюквой. Фирменная ягодная горчинка прилагается, преимущественно проявляя себя в послевкусии. Избежать ярких эмоций не удастся! Вкус для тех, кто хочет проснуться и зажечь.\n\nЯркая клюквенная терпкость раскрывает свои грани во всей полноте. Табачная основа из крепкого Burley дымит в сторонке, образуя густые облака, в лучших традициях Burn.\n\nКрепость у листа неслабая — позволяет играть с забивками, чашами, экспериментировать и наслаждаться. Жаростойкость — огонь, восстановление вкуса после перегрева — легко (не то, что после ковида), расслабление — непреодолимой силы.",
      "summaryRu": "Кислая клюква",
      "family": "Shock",
      "tags": [
        "cranberry",
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "573711814681",
      "slug": "cre-me-bru-le-e",
      "title": "Crème Brûlée",
      "descriptionRu": "Изюминка десерта Крем-Брюле в его карамельной хрустящей корочке. Именно этот вкус с нотками кремовой, сливочной основы десерта мы перенесли во вкус BlackBurn Crème Brûlée. Оригинальный рецепт десерта обязательно содержит ваниль и если вы гурман кальянных табаков, то тоже обязательно обнаружите вкус ванили в BlackBurn Crème Brûlée.",
      "summaryRu": "Десерт Крем Брюле",
      "family": "Shock",
      "tags": [
        "cream",
        "pastry"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "379308046701",
      "slug": "ekzo-mango",
      "title": "Ekzo Mango",
      "descriptionRu": "Манго — король экзотических фруктов, обладающий и приятной сливочностью, и чуть ощутимой травянистостью. В BlackBurn Ekzo Mango помимо этих вкусовых особенностей вы найдете и легкую кислинку. Именно такой палитрой и должен обладать лучший манго в индустрии.",
      "summaryRu": "Сочное манго",
      "family": "Shock",
      "tags": [
        "tropical-fruit",
        "herbal",
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "493457759631",
      "slug": "elderberry-shock",
      "title": "Elderberry Shock",
      "descriptionRu": "Задорно-кислый аромат неподражаемых ягод бузины с терпким, но сладковатым нюансом. Шокирует вкусовые рецепторы похлеще легендарных конфет Shock из лихих 90-х.",
      "summaryRu": "Кислая бузина",
      "family": "Shock",
      "tags": [
        "berry",
        "candy",
        "elderberry"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "890636499541",
      "slug": "epic-yogurt",
      "title": "Epic Yogurt",
      "descriptionRu": "Натуральный черничный йогурт с нежнейшей текстурой. Воздушный, сливочный и в меру ягодный.",
      "summaryRu": "Черничный йогурт",
      "family": "Shock",
      "tags": [
        "berry",
        "cream",
        "yoghurt",
        "cucumber"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "934502215471",
      "slug": "etalon-melon",
      "title": "Etalon Melon",
      "descriptionRu": "Насыщенный сладкий вкус спелой дыни с мягким медовым послевкусием. Непревзойденная классика теперь и в BlackBurn!\nНасладись естесственным ароматом солнечного фрукта с BlackBurn Etalon Melon.",
      "summaryRu": "Медовая дыня",
      "family": "Shock",
      "tags": [
        "honey"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "571577198871",
      "slug": "famous-apple",
      "title": "Famous Apple",
      "descriptionRu": "Универсальный вкус, подходящий под любой микс и для курения соло. Ощущение, что гуляешь по яблоневому саду на рассвете, когда еще не сошла утренняя прохлада. Чуть сладковатый с характерной кислинкой для яблока вкус узнаваем с первого вдоха.",
      "summaryRu": "Ледяное зеленое яблоко",
      "family": "Original",
      "tags": [
        "cooling",
        "apple"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "990608483941",
      "slug": "feijoa-jam",
      "title": "Feijoa Jam",
      "descriptionRu": "Вы по-настоящему насладитесь ароматом очень сладкого варенья из фейхоа. Если вы любите сладкие или даже десертные вкусы, обязательно попробуйте Feijoa Jam!",
      "summaryRu": "Варенье из фейхоа",
      "family": "Shock",
      "tags": [
        "feijoa",
        "pastry"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "676025520211",
      "slug": "garnet",
      "title": "Garnet",
      "descriptionRu": "Garnet удовлетворит любого гурмана. Приятный, экзотический, в меру кислый вкус граната отлично подойдет для любых фруктовых кальянных миксов, а также неплохо курится соло. С приятной терпкой ноткой и богатым фруктовым послевкусием хорошо бодрит, необычный вкус однозначно стоит пробовать всем любителям кисленького.",
      "summaryRu": "Терпкий гранат",
      "family": "Original",
      "tags": [
        "tropical-fruit",
        "pomegranate"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "537015900862",
      "slug": "grapefruit",
      "title": "Grapefruit",
      "descriptionRu": "Душистый аромат мякоти сочного грейпфрута с легкой горчинкой\nМы выжали весь сок из мякоти грейпфрута, освежили его ароматом и легкой горечью цедры, и упаковали его в фирменные банки. Прочувствуйте многогранность грейпфрута в новом BLACKBURN Grapefruit.",
      "summaryRu": "Грейпфрут",
      "family": "Original",
      "tags": [
        "grapefruit",
        "grape"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "990469141861",
      "slug": "green-tea",
      "title": "Green Tea",
      "descriptionRu": "Мягкий аромат табака BlackBurn - Green Tea погрузит в расслабляющую атмосферу. Приятный, бархатный вкус зеленого чая соблазняюще ароматен, табак курится легко и оставляет приятное послевкусие. Прекрасно тонизирует, к нему прекрасно подойдет выпечка, а также миксы с лаймом, малиной, базиликом и яблоком.",
      "summaryRu": "Зеленый чай",
      "family": "Original",
      "tags": [
        "apple",
        "raspberry",
        "basil",
        "herbal",
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "959475223211",
      "slug": "haribon",
      "title": "Haribon",
      "descriptionRu": "Вкус сладких мармеладных конфеток со вкусом шипящей кока-колы. Отлично курится в соло, в миксах можно добавлять апельсин, лимон или алкогольные вкусы.",
      "summaryRu": "Мармеладные конфеты со вкусом шипящей кока-колы",
      "family": "Original",
      "tags": [
        "lemon",
        "orange",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "408137598101",
      "slug": "iceberg",
      "title": "Iceberg",
      "descriptionRu": "Вы смотрели фильм «Послезавтра»? Помните момент, когда поток воздуха мгновенно замораживал все на своем пути: вертолеты, здания … также и Iceberg от BlackBurn.\n\nIceberg буквально замораживает вас, пронизывая каждую клетку организма, даря неповторимое ощущение прохлады и свежести, как будто бы вы оказались на ледяных просторах Арктики.\n\nЭто дым величественного модерна, который переносит вас в захватывающее приключение движущихся айсбергов и волшебства ледяных пещер.\n\nПробудите свое воображение и погрузитесь в освежающий мир \"Арктического льда\".",
      "summaryRu": "Арктический лед",
      "family": "Original",
      "tags": [
        "cooling"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "216618625491",
      "slug": "irish-cream",
      "title": "Irish Cream",
      "descriptionRu": "Вкус ирландского крема с высокой крепостью и многообразием вкусовых ощущений. Ценители непревзойденных вкусов оценят по достоинству вкус ирландского виски с ароматом нежных сливок. А шоколадное послевкусие на выходе принесет немало удовольствия.",
      "summaryRu": "Ирландский сливочный крем",
      "family": "Original",
      "tags": [
        "cream",
        "cacao",
        "cola",
        "spices"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "879039947371",
      "slug": "juicy-smoothie",
      "title": "Juicy Smoothie",
      "descriptionRu": "Все ингредиенты Juicy Smoothie от BlackBurn взбиты в невероятно сочный смузи, в котором яркая клубника дополняется папайей, а стружка тропического кокоса придает окончательную форму этой вкусовой композиции. Наслаждайтесь!",
      "summaryRu": "Тропический смузи",
      "family": "Original",
      "tags": [
        "strawberry",
        "papaya",
        "tropical-fruit",
        "coconut",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "774214157361",
      "slug": "kiwi-stoner",
      "title": "Kiwi Stoner",
      "descriptionRu": "Интересный и даже интригующий кисло-сладкий вкус. Освежает и поднимает настроение. Отличный выбор для жаркого дня, чтобы немного взбодриться и переключиться.\n\nПревосходно заходит соло, отдавая в послевкусии даже сладковатые нотки. А в целом — убойно кисленько. Если добавить холодка и мяты, получится вообще фееричный «замес».\n\nBlackBurn на основе листьев Burley довольно крепкий, но можно немного «разрядить обстановку» более плотной забивкой.\nНарезка отличная, средняя, сиропность оптимальная, вкус и аромат смесь отдает с первого вдоха.",
      "summaryRu": "Смузи из киви",
      "family": "KMTM",
      "tags": [
        "cooling",
        "mint"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "437907794241",
      "slug": "lemon-shock",
      "title": "Lemon Shock",
      "descriptionRu": "Лимон, настоящий ЛИМОН. Никаких конфетных историй, леденцов и прочего! Только кислый вкус, только хардкор.\nLemon SHOCK - это универсальный аромат годный к использованию в миксах и крайне хорош в соло.",
      "summaryRu": "Кислый лимон",
      "family": "Shock",
      "tags": [
        "cooling",
        "lemon",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "113892723841",
      "slug": "lemon-sweets",
      "title": "Lemon Sweets",
      "descriptionRu": "Неожиданная подача классического лимонного вкуса - нежный сладковатый оттенок лимона с добавлением цитрусовых. На выдохе во рту сохранятся нотка лимонной карамели, кислинка в данном табаке не ярко выраженная, поэтому он придется по душе тем, кто любит легкие сладковатые вкусы. Приятно курится в чистом виде и сочетается с различными миксами фруктовой, чайной и десертной тематики, а также готов к созданию неожиданной палитры вкуса, например, в дуэте с \"Клубничным вареньем\".",
      "summaryRu": "Лимонные леденцы",
      "family": "Original",
      "tags": [
        "cooling",
        "lemon",
        "citrus",
        "herbal",
        "pastry",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "932271392972",
      "slug": "lulo",
      "title": "Lulo",
      "descriptionRu": "Луло — незабываемый вкус экзотического ки́тосского паслёна. Аромат сочной мякоти с легкой кислинкой, гармонично сочетающий сразу несколько фруктов: ананас, маракуйю, апельсин и клубнику, с нежными сливочными оттенками. Этот вкус никого не оставит равнодушным и впечатлит даже самых искушённых любителей экзотики.",
      "summaryRu": "Луло",
      "family": "Original",
      "tags": [
        "orange",
        "pineapple",
        "strawberry",
        "passion-fruit",
        "tropical-fruit",
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "580027063761",
      "slug": "malibu",
      "title": "Malibu",
      "descriptionRu": "Клубничные острова в море сливок — это Malibu от BlackBurn. Сладкое,\nсливочное, клубничное наслаждение накрывает тебя с каждым вдохом Malibu.\nМы все знаем этот вкус благодаря красно-белым карамелькам Малибу, а\nтеперь его легко ощутить, забив чашечку BlackBurn Malibu.",
      "summaryRu": "Леденец Малибу",
      "family": "Original",
      "tags": [
        "cooling",
        "coconut",
        "cream",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "137424322221",
      "slug": "melon-halls",
      "title": "Melon Halls",
      "descriptionRu": "Фирменный вкус леденцов с двойным эффектом: свежесть и наслаждение вкусом ароматной Дыни!\nMelon Halls это новый вкус в крепкой линейке BlackBurn, который великолепно проявляет себя как в соло, так и в различных миксах.\nMelon Halls - cочно, дымно, крепко! Успей попробовать первым!",
      "summaryRu": "Дынный холс",
      "family": "Original",
      "tags": [
        "cooling",
        "candy"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "150802823161",
      "slug": "mirinda",
      "title": "Mirinda",
      "descriptionRu": "Яркая цитрусовая газировка с насыщенными вкусами апельсина, мандарина и кислинкой сладкого лимона.\nОсвежи настроение с новым невероятно сочным вкусом BlackBurn Mirinda.",
      "summaryRu": "Мандариновая газировка",
      "family": "Original",
      "tags": [
        "lemon",
        "orange",
        "citrus"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "313894799541",
      "slug": "muesli",
      "title": "Muesli",
      "descriptionRu": "Молочно-овсяные мюсли с персиковым джемом и душистой земляникой.\nЗавтрак станет удивительно вкусным и быстрым благодаря новому вкусу Muesli от BlackBurn.",
      "summaryRu": "Фруктовые мюсли",
      "family": "Original",
      "tags": [
        "peach",
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "439517736251",
      "slug": "nutella",
      "title": "Nutella",
      "descriptionRu": "Шоколадно-ореховая паста",
      "summaryRu": "Шоколадно-ореховая паста",
      "family": "Original",
      "tags": [
        "cacao",
        "cola"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "368841204561",
      "slug": "overdose",
      "title": "Overdose",
      "descriptionRu": "Взрывной хит 2021 года - крепкий и сочный вкус, сочетающий в себе кислые ноты сочного лимона и дерзкого лайма! Отлично подойдет для создания классных цитрусовых миксов!\nОсторожно! Высокая крепость 10/10\n\nПрогревать на 4 х 25 мм углях 5-6 минут (у продукта повышенная жаростойкость)\nКрепость продукта раскрывается только на протяжении всего сеанса, а не в первые минуты, что позволяет комфортно наслаждаться процессом и получать максимальное расслабление.",
      "summaryRu": "Взрывной хит 2021 года - крепкий и сочный вкус, сочетающий в себе кислые ноты сочного лимона и дерзкого лайма! Отлично подойдет для создания классных цитрусовых миксов!\nОсторожно! Высокая крепость 10/10\n\nПрогревать на 4 х 25 мм углях 5-6 минут (у продукта повышенная жаростойкость)\nКрепость продукта раскрывается только на протяжении всего сеанса, а не в первые минуты, что позволяет комфортно наслаждаться процессом и получать максимальное расслабление.",
      "family": "Original",
      "tags": [
        "lemon",
        "citrus"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "416917711641",
      "slug": "papaya-v-obed",
      "title": "Papaya V Obed",
      "descriptionRu": "Один из четырех вкусов, выпущенный в коллаборации с известным кальянным блогером Слава КМТМ (Кальянный Мастер Твоей Мамы). Это сочный и травянистый вкус папайи с легкими нотками сливочности и кислинкой.",
      "summaryRu": "Яркая папайя",
      "family": "KMTM",
      "tags": [
        "papaya",
        "herbal",
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "978321571121",
      "slug": "peach-killer",
      "title": "Peach Killer",
      "descriptionRu": "Роскошный, насыщенный вкус сладкой и нежной мякоти персика. Яркое и приятное послевкусие, ароматный дым. Peach Killer отлично сочетается практически со всеми с другими фруктовыми вкусами.",
      "summaryRu": "Бархатный персик",
      "family": "Original",
      "tags": [
        "peach"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "126635559121",
      "slug": "peach-yogurt",
      "title": "Peach Yogurt",
      "descriptionRu": "Персиковый йогурт",
      "summaryRu": "Персиковый йогурт",
      "family": "Original",
      "tags": [
        "peach",
        "yoghurt",
        "cucumber"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "259246939021",
      "slug": "peachberry",
      "title": "Peachberry",
      "descriptionRu": "Темный Burn снова ставит на беспроигрышные сочетания. В этот раз непревзойденно-ароматная земляника родом из леса и лета разбавляет свою дерзкую пряность нежной сочностью избалованного южным солнцем персика.\n\nДуэт, прямо скажем, \"Вау!\" — идеально ложится на любой повод и настроение. Повышает тонус, настраивает на теплую, \"прогретую\" дымом атмосферу.\n\nРасслабиться поможет отборный темный Burley, который своей крепостью придаст чиллу нужный колорит и жаркое звучание.\nТабак хорошо ведет себя на разных забивках, открывает возможности для экспериментов, заходит тем, кто ценит кальян покрепче.",
      "summaryRu": "Земляника и персик",
      "family": "Original",
      "tags": [
        "peach",
        "berry",
        "spices"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "163936864361",
      "slug": "pear-lemonade",
      "title": "Pear Lemonade",
      "descriptionRu": "Безупречный бленд груши, льда и мяты. Прекрасный яркий летний вкус для жарких вечеров, для тех, кто предпочитает что-то свежее.",
      "summaryRu": "Грушевый лимонад",
      "family": "Original",
      "tags": [
        "lemon",
        "mint",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "432110049801",
      "slug": "pinacolada",
      "title": "Pinacolada",
      "descriptionRu": "Яркий солнечный вкус классического карибского коктейля, мастерски составленного из насыщенных оттенков свежего ананасового сока и нежного кокосового молока, что буквально тает во рту.",
      "summaryRu": "Пина-колада",
      "family": "Original",
      "tags": [
        "pineapple",
        "coconut",
        "cola",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "293538294341",
      "slug": "pineapple",
      "title": "Pineapple",
      "descriptionRu": "Сочный спелый ананас - король тропических фруктов. Универсальный кисловато-сладкий вкус. Прекрасно используется как в соло, так и в миксах с любыми вкусами.",
      "summaryRu": "Сочный ананас",
      "family": "Original",
      "tags": [
        "apple",
        "pineapple",
        "tropical-fruit"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "555592676032",
      "slug": "pineapple-yogurt",
      "title": "Pineapple Yogurt",
      "descriptionRu": "Нежный, сливочный вкус ананасового йогурта\n\nСливочный йогурт с ярким вкусом спелого ананаса. Мы взяли тающий во рут сладкий ананас и смешали его с натуральным йогрутом, чтобы получить очередной хитовый вкус. Мягкий и сладкий, он добавит нежные и сбалансированный нотки в ваши чашки. BLACKBURN Pineapple Yogurt - больше, чем йогурт.",
      "summaryRu": "Ананасовый йогурт",
      "family": "Original",
      "tags": [
        "apple",
        "pineapple",
        "cream",
        "yoghurt",
        "cucumber"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "484374216121",
      "slug": "pistachio-ice-snow",
      "title": "Pistachio Ice Snow",
      "descriptionRu": "Фисташковое мороженое - то, что нужно для лета!\nPistachio Ice Snow потрясающе холодный, но в то же время очень нежный орехово-сливочный вкус, положенный на табачный лист сорта Toasted Burley.\n\nPistachio Ice Snow - это магия крепкого BlackBurn, от которой появляются мурашки! Спешите попробовать!",
      "summaryRu": "Фисташковое мороженое",
      "family": "Original",
      "tags": [
        "cooling",
        "cream",
        "ice-cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "657198892332",
      "slug": "pomelo",
      "title": "Pomelo",
      "descriptionRu": "Тот самый вкус помело: терпкий, кисло-сладкий, с горьковатыми нотками.\nBLACKBURN Pomelo – это классический насыщенный вкус помело, кисло-сладкий на вдохе и с приятной горечью на выдохе. Летняя тарелка с дольками изысканного, освежающего вкуса любимого многими тропического фрукта.",
      "summaryRu": "Помело",
      "family": "Original",
      "tags": [
        "grapefruit",
        "tropical-fruit",
        "fir"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "632122627621",
      "slug": "pudding",
      "title": "Pudding",
      "descriptionRu": "Пуддинг",
      "summaryRu": "Пуддинг",
      "family": "Original",
      "tags": [
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "249979192831",
      "slug": "raspberries",
      "title": "Raspberries",
      "descriptionRu": "Cладкая ароматная малина с небольшой приятной кислинкой на послевкусии. Очень легко и приятно курится в соло. После курения остается мягкое послевкусие, а сладкий, свежий аромат понравится не только курящим, но и окружающим.",
      "summaryRu": "Спелая лесная малина",
      "family": "Original",
      "tags": [
        "raspberry"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "176459686391",
      "slug": "raspberry-shock",
      "title": "Raspberry Shock",
      "descriptionRu": "Кислая малина",
      "summaryRu": "Кислая малина",
      "family": "Shock",
      "tags": [
        "raspberry",
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "177991222861",
      "slug": "real-p-f",
      "title": "REAL P.F.",
      "descriptionRu": "Нереальный тропический вкус напомнит забытые оттенки подогретого солнцем берега моря. Яркий вкус маракуйи с харизматичной пряной сладостью и кислинкой доставит вас прямиком на дымные облака наслаждения.\nЯркий, настоящий: не то, что путешествия 2020. Красочный фейерверк на карте будней!\n\nНасыщенные нотки дополняет табачный темный лист Burley, приносящей усталым людям и скучным вечерам нужный градус расслабления. Повышенная крепость табака не выдает себя во вкусе, тает в мягких облаках дыма.\n\nТабак переносит любые перепады со вкусом, отлично миксуется, обладает умеренной сиропностью, долго сохраняет насыщенность ароматики и дыма, в забивках непривередлив.",
      "summaryRu": "Настоящая маракуйя",
      "family": "Original",
      "tags": [
        "passion-fruit",
        "tropical-fruit",
        "spices"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "731851438631",
      "slug": "red-currant",
      "title": "Red Currant",
      "descriptionRu": "Красная смородина Burn сегодня не позволит вам заскучать. Ягодные оттенки сводят скулы у всех, кто чилил летом в деревне или на даче. Кислые нотки без пряности, но с легкой сладостью — это американские вкусовые горки + много дыма.\n\nНасыщенность ягоды обеспечена натуральными ароматизаторами (даже бабушка не отличит). Крепости добавляет темный и лучший Burley, своим мягким характером покоривший немало сердец. Подходит тем, кто уже давно в кальянной теме.\n\nВкусопередача начнется по расписанию, сразу после свежей забивки. В перерывах густой туман и повышенное расслабление.",
      "summaryRu": "Красная смородина",
      "family": "Original",
      "tags": [
        "berry",
        "lychee",
        "spices"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "912171930992",
      "slug": "red-energy",
      "title": "Red Energy",
      "descriptionRu": "Классический вкус любимого энергетического напитка\nИстинное воплощение энергии и страсти. Щедрая сладость переплетается со свежестью и манит своей непринужденностью. В каждом вдохе бурлящей энергии вибрирует легкая кислинка, придающая напитку искрящийся оттенок. BLACKBURN Red Energy - энергия твоей ночи.",
      "summaryRu": "Энергетик",
      "family": "Original",
      "tags": [
        "beverage"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "159203906072",
      "slug": "red-kiwi",
      "title": "Red Kiwi",
      "descriptionRu": "Кисло-сладкая эйфория сочного киви с нотками арбуза и клубники.\nВосхитительно-сладкий вкус яркой красной мякоти киви с ягодным оттенком клубники и нотками арбуза. Летний шарм и освежающая сочность настоящего красного киви.",
      "summaryRu": "Красный киви",
      "family": "Original",
      "tags": [
        "strawberry",
        "berry",
        "watermelon"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "323782730111",
      "slug": "red-orange",
      "title": "Red Orange",
      "descriptionRu": "Вкус экзотического красного апельсина. Кислый и одновременно сладкий, безумно ароматный и насыщенный.",
      "summaryRu": "Красный апельсин",
      "family": "Original",
      "tags": [
        "orange",
        "tropical-fruit"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "584163316791",
      "slug": "rising-star",
      "title": "Rising Star",
      "descriptionRu": "Микс для любителей сладкого и тропического, как ароматный коктейль, бережно собранный для вас на песочном берегу океана или в вечернем баре перед бассейном.\nСладкие нотки манго в сочетании с ароматом маракуйи определенно выделяют этот вкус из всей фруктовой линейки BlackBurn.",
      "summaryRu": "Манго маракуйя",
      "family": "Original",
      "tags": [
        "passion-fruit",
        "tropical-fruit",
        "beverage"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "406235441872",
      "slug": "salak",
      "title": "Salak",
      "descriptionRu": "Змеиный фрукт — это нежный, свежий вкус салака. Напоминает одновременно и ананас, и банан, а также немного вяжет. На выдохе согревает легким ореховым привкусом. Аромат перемещает на Юг, в атмосферу тропического отдыха. Впечатлит любителей экзотики и не оставит равнодушным.",
      "summaryRu": "Змеиный фрукт",
      "family": "Original",
      "tags": [
        "pineapple",
        "banana",
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "774902826561",
      "slug": "shock-currant-shock",
      "title": "Shock, Currant Shock",
      "descriptionRu": "Вариант однозначно для любителей смородины. Из открытой упаковки терпкий и пряный запах смородины распространяется на всю комнату. Как будто только что сорванная свежая смородина лежит на столе.\n\nВ процессе вдыхания дает приятный кислый вкус с выраженными смородиновыми нотами. Кислит и освежает как надо. Вкус сохраняется продолжительно, не надоедает, хотя можно попробовать замиксовать и добавить и сладких акцентов.\n\nНо и так вкус многогранный, интересный за счет кислинки и терпкости, не мыльный. Травянистые вкрапления приносят какое-то «лесное настроение».\n\nСмесь насыщенная и крепкая, положена на основу темного сорта Burley, что дает более быстрый эффект, чем Virginia, и подходит больше для тех, кто «уже в теме». Жаростойкость оптимальная: перегревов не боится, быстро восстанавливается, вкусопередача на высоте.",
      "summaryRu": "Кислая черная смородина",
      "family": "Shock",
      "tags": [
        "blackcurrant",
        "berry",
        "herbal",
        "spices"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "827322914121",
      "slug": "siberian-soda",
      "title": "Siberian Soda",
      "descriptionRu": "Напиток, вдохновленный бескрайними сибирскими лесами. В одном стакане соединились отчетливые нотки хвои с небольшим оттенком колы, переносящие вас в самые отдаленные края природы. Вкус, в котором воет ветер и шуршат ели.",
      "summaryRu": "Лимонад \"Байкал\"",
      "family": "Original",
      "tags": [
        "lemon",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "796326211112",
      "slug": "skittles",
      "title": "Skittles",
      "descriptionRu": "BLACKBURN Skittles – яркий, взрывной, кислый вкус конфет Скиттлс.\nЛюбимые кисло-сладкие конфеты, приятно щиплющие язык и оставляющие легкое цитрусовое послевкусие. Вспомните детство и погрузитесь в атмосферу игривой беззаботности: этот вкус всколыхнет самые яркие воспоминания и заставит почувствовать радостную легкость.",
      "summaryRu": "Скиттлс",
      "family": "KMTM",
      "tags": [
        "citrus",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "774195539061",
      "slug": "something-berry",
      "title": "Something Berry",
      "descriptionRu": "Любите что-то ягодное? Тогда выбирайте Something Berry - богатый кисло-сладкий аромат сочных ягод с терпкими, цветочными и травянистыми оттенками. Улавливаются насыщенные ноты черники, ежевики, малины, крыжовника, боярышника, красной и черной смородины.\nИдеален в соло, но и отлично миксуется с мятными, чайными, десертными и фруктовыми ароматами.",
      "summaryRu": "Что-то ягодное",
      "family": "Something",
      "tags": [
        "raspberry",
        "blackberry",
        "blackcurrant",
        "berry",
        "mint",
        "herbal",
        "pastry"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "882754629641",
      "slug": "something-tropical",
      "title": "Something Tropical",
      "descriptionRu": "Попробуйте мощный и сногсшибательный микс из тропических фруктов в табаке BlackBurn - Something Tropical. Насладитесь ярким и многогранным букетом с преобладающими нотками ананаса, манго, питахайи, маракуйи, карамболы, лонгана, мангустина и лайма. Отличный кисло-сладкий аромат с легкими терпкими, цветочными и травянистыми оттенками.",
      "summaryRu": "Что-то тропическое",
      "family": "Something",
      "tags": [
        "pineapple",
        "passion-fruit",
        "tropical-fruit",
        "herbal"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "540628500401",
      "slug": "sou-sep",
      "title": "Sou-Sep",
      "descriptionRu": "Освежающий глоток прохладного тархуна будоражит рецепторы травянистым ароматом детства, который идеально сочетается со сметанными нотками тропического саусепа: экзотического сахарного яблока, обладающего дивным кисло-сладким послевкусием.",
      "summaryRu": "Зеленый лимонад",
      "family": "Original",
      "tags": [
        "lemon",
        "apple",
        "tropical-fruit",
        "herbal",
        "beverage"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "920636360111",
      "slug": "strawberry-coconut",
      "title": "Strawberry Coconut",
      "descriptionRu": "Витаминный заряд из освежающего микса спелой клубники и экзотического кокоса, приправленный прохладно-терпким ароматом эвкалипта.",
      "summaryRu": "Клубника, кокос, эвкалипт",
      "family": "Original",
      "tags": [
        "strawberry",
        "berry",
        "tropical-fruit",
        "coconut"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "981062849971",
      "slug": "strawberry-jam",
      "title": "Strawberry Jam",
      "descriptionRu": "BlackBurn Strawberry Jam со вкусом клубничного варенья, для любителей ягодной классики. Обладает приятным, легким ароматом, очень сладкий на вкус с нотками ягодных вкраплений. Вкус варенья придает ему еще больше насыщенности, но без сильной приторности. Попробуйте собрать свое ягодное лукошко с черникой, клюквой и щепоткой мяты или холодка.",
      "summaryRu": "Клубничный джем",
      "family": "Original",
      "tags": [
        "cooling",
        "strawberry",
        "cranberry",
        "berry",
        "mint"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "260026344201",
      "slug": "summer-basket",
      "title": "Summer Basket",
      "descriptionRu": "Какое лето без фруктов! Ни один пикник не обойдется без фруктовой корзинки BlackBurn! Новое сочетание сахарного арбуза, сладкого ягодного смузи с преобладанием малины и сочного апельсина, завершающего композицию. А что в твоей корзинке? Summer Basket туда идеально впишется!",
      "summaryRu": "Ягодная корзина",
      "family": "Original",
      "tags": [
        "orange",
        "raspberry",
        "berry",
        "watermelon"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "902644499451",
      "slug": "sundaysun",
      "title": "Sundaysun",
      "descriptionRu": "Насыщенный, свежий и ароматный летний коктейль из цитрусовых фруктов - лимона, апельсина и грейпфрута. Один из лучших цитрусовых миксов!",
      "summaryRu": "Цитрусовый микс",
      "family": "Original",
      "tags": [
        "lemon",
        "orange",
        "grapefruit",
        "citrus",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "322916015221",
      "slug": "tik-tak",
      "title": "Tik Tak",
      "descriptionRu": "Апельсиновый вкус маленьких драже из детства. Таят во рту, как свежие дольки апельсина, наполненные сладостью и сочностью цитруса.\nЕсли бы банка Tik Tak была круглой, ты бы и не заметил разницы между настоящим драже и вкусом BlackBurn!",
      "summaryRu": "Драже из детства",
      "family": "Original",
      "tags": [
        "orange",
        "citrus",
        "mint"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "301965310321",
      "slug": "tropic-jack",
      "title": "Tropic Jack",
      "descriptionRu": "Тропик, который создал Джееек. Потрясающе нежный вкус экзотического джекфрута, соединивший в себе нотки пастилы, банана и ананаса. Это один из самых популярных фруктов Юго-Восточной Азии, но пробовал ли ты его? Мы здесь, чтобы приблизить тебя к экзотике и подарить сладко-тропическое вдохновение!",
      "summaryRu": "Спелый Джекфрут",
      "family": "Original",
      "tags": [
        "pineapple",
        "banana",
        "tropical-fruit"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "784533445411",
      "slug": "watermelon",
      "title": "Watermelon",
      "descriptionRu": "Классика в новом исполнении. Сочный спелый арбуз, поражающий своей сахарной основой. И главное: никаких косточек!",
      "summaryRu": "Сладкий арбуз",
      "family": "Original",
      "tags": [
        "watermelon"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "255320732641",
      "slug": "e-lka",
      "title": "Ёlka",
      "descriptionRu": "Пронзительный смолистый аромат елки с легкой свежестью и нотой эвкалипта. Насладись новым освежающим травянистым вкусом Ëlka от BLACKBURN!",
      "summaryRu": "Ёлка",
      "family": "Shock",
      "tags": [
        "herbal",
        "fir"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "870961101401",
      "slug": "na-rasslabone",
      "title": "На расслабоне",
      "descriptionRu": "«На расслабоне» - один из двух коллаборационных вкусов BLACKBURN x Джиган. Нежнейшее банановое суфле расслабляет, перенося вас на райское солнечное побережье под пальму жарким летним днем.\nСпелый банан, взбитый в мягчайший десерт.\nОткрываем сезон «расслабона» этим летом!",
      "summaryRu": "Банановое суфле",
      "family": "Original",
      "tags": [
        "banana",
        "herbal",
        "pastry"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "134223456101",
      "slug": "na-chille",
      "title": "На чилле",
      "descriptionRu": "Новый коллаборационный вкус BLACKBURN x Джиган - это насыщенное сочетание спелого ананаса и кисло-сладкой маракуйи. Как если бы мы выжали весь сок из мякоти фруктов и упаковали его в наши фирменные банки.\nБудь как Джиган на чилле с BLACKBURN",
      "summaryRu": "Тропический сок",
      "family": "Original",
      "tags": [
        "pineapple",
        "passion-fruit",
        "tropical-fruit"
      ],
      "sweetness": "pronounced",
      "acidity": "pronounced",
      "freshness": "subtle"
    }
  ]
};
