import type { CatalogSource, SeedBrand, SeedProduct } from "./catalog-v1.js";
export const mixSupportSourcesV3:CatalogSource[]=[
 {key:"musthave-rocketman",url:"https://musthave.ru/tabak-dlya-kalyana-musthave-rocketman/",title:"Рокетмен (Rocketman)",publisher:"MUSTHAVE",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",sourceType:"official_catalog",notes:"Official product page with name and flavor notes."},
 {key:"musthave-strawberry-lychee",url:"https://musthave.ru/tabak-dlya-kalyana-musthave-strawberry-lychee/",title:"Земляника и личи (Strawberry-Lychee)",publisher:"MUSTHAVE",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",sourceType:"official_catalog",notes:"Official product page with name and flavor notes."},
 {key:"musthave-drinks",url:"https://musthave.ru/category/tabak-dlya-kalyana/napitki/",title:"Напитки",publisher:"MUSTHAVE",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",sourceType:"official_catalog",notes:"Official category listing for Tropic Juice and Prosecco."},
 {key:"musthave-mandarin",url:"https://musthave.ru/tabak-dlya-kalyana-musthave-mandarin/",title:"Мандарин (Mandarin)",publisher:"MUSTHAVE",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",sourceType:"official_catalog",notes:"Official product page with name and flavor notes."},
 {key:"musthave-cream-soda",url:"https://musthave.ru/tabak-dlya-kalyana-musthave-cream-soda/",title:"Крем сода (Cream Soda)",publisher:"MUSTHAVE",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",sourceType:"official_catalog",notes:"Official product page with name and flavor notes."}
];
const p=(slug:string,en:string,ru:string,sourceKey:string,tags:string[],fresh=false):SeedProduct=>({slug,nameEn:en,nameRu:ru,sourceKey,tags,translationOrigin:"official",sweetness:"pronounced",acidity:"subtle",freshness:fresh?"pronounced":"subtle"});
export const mixSupportBrandsV3:SeedBrand[]=[{slug:"musthave",name:"MUSTHAVE",sourceKey:"musthave-catalog",lines:[{slug:"original",name:"Original",strength:"medium",sourceKey:"musthave-catalog",products:[
 p("rocketman","Rocketman","Рокетмен","musthave-rocketman",["strawberry","grapefruit","beverage"],true),p("strawberry-lychee","Strawberry-Lychee","Земляника и личи","musthave-strawberry-lychee",["strawberry","lychee"]),p("tropic-juice","Tropic Juice","Тропический сок","musthave-drinks",["tropical-fruit","beverage"]),p("prosecco","Prosecco","Просекко","musthave-drinks",["grape","beverage"]),p("mandarin","Mandarin","Мандарин","musthave-mandarin",["orange","pastry"]),p("cream-soda","Cream Soda","Крем сода","musthave-cream-soda",["vanilla","cream","beverage"])
]}]}];
