import type { CatalogSource, SeedBrand, SeedProduct } from "./catalog-v1.js";

export const sourcesV2: CatalogSource[] = [
  { key:"brusko-official",url:"https://www.brusko.ru/catalog/tobacco",title:"BRUSKO Tobacco",publisher:"BRUSKO",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Official catalog exposes 26 current flavors, descriptions and medium line strength." },
  { key:"duft-industry",url:"https://hookahportal.ru/tobaccos/duft",title:"Табаки — Duft",publisher:"Hookah Portal",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"medium",notes:"Industry catalog used because the manufacturer catalog is not reliably accessible; no commerce data collected." },
  { key:"daily-industry",url:"https://hookahportal.ru/tobaccos/daily-hookah",title:"Табаки — Daily Hookah",publisher:"Hookah Portal",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"medium",notes:"Industry catalog used for current product labels and facets; no commerce data collected." },
  { key:"blackburn-official",url:"https://www.blckburn.com/",title:"BlackBurn Tobacco",publisher:"Burn Tobacco",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Official source confirms the brand and active product families; flavor menu is image-driven." },
  { key:"blackburn-industry",url:"https://hookahportal.ru/tobaccos/blackburn",title:"Табаки — BlackBurn",publisher:"Hookah Portal",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"medium",notes:"Industry catalog fallback for exact flavor labels/facets because official flavor cards are image-driven; no commerce data collected." }
];

const p = (slug:string,nameEn:string,nameRu:string,sourceKey:string,tags:string[], acidity=false, freshness=false): SeedProduct => ({ slug,nameEn,nameRu,sourceKey,tags,translationOrigin:"normalized_translation",sweetness:"pronounced",acidity:acidity ? "pronounced":"subtle",freshness:freshness ? "pronounced":"subtle" });

export const brandsV2: SeedBrand[] = [
  {slug:"brusko",name:"BRUSKO",sourceKey:"brusko-official",lines:[{slug:"tobacco",name:"Tobacco",strength:"medium",sourceKey:"brusko-official",products:[
    p("orange","Orange","Апельсин","brusko-official",["orange"]),p("bubble-gum","Bubble Gum","Бабл-гам","brusko-official",["candy"]),p("banana","Banana","Банан","brusko-official",["banana"]),p("barberry","Barberry","Барбарис","brusko-official",["berry"],true),p("grape","Grape","Виноград","brusko-official",["grape"]),p("cherry","Cherry","Вишня","brusko-official",["cherry"],true),p("pomegranate","Pomegranate","Гранат","brusko-official",["pomegranate"],true),p("grapefruit-raspberry","Grapefruit & Raspberry","Грейпфрут с малиной","brusko-official",["grapefruit","raspberry"],true),p("cinnamon-dessert","Cinnamon Dessert","Десерт с корицей","brusko-official",["pastry","cinnamon"]),p("melon-watermelon","Melon & Watermelon","Дыня с арбузом","brusko-official",["watermelon","tropical-fruit"]),p("kiwi","Kiwi","Киви","brusko-official",["tropical-fruit"],true),p("strawberry","Strawberry","Клубника","brusko-official",["strawberry"]),p("cola","Cola","Кола","brusko-official",["cola","beverage"]),p("forest-berries","Forest Berries","Лесные ягоды","brusko-official",["berry","raspberry","blueberry"]),p("lemon-lime","Lemon & Lime","Лимон с лаймом","brusko-official",["lemon","citrus"],true,true)
  ]}]},
  {slug:"duft",name:"Duft",sourceKey:"duft-industry",lines:[{slug:"original",name:"Original",strength:"medium",sourceKey:"duft-industry",products:[
    p("cherry-juice","Cherry Juice","Вишнёвый сок","duft-industry",["cherry","beverage"],true),p("pineapple","Pineapple","Ананас","duft-industry",["pineapple"]),p("maracuja","Maracuja","Маракуйя","duft-industry",["passion-fruit"],true),p("pink-grapefruit","Pink Grapefruit","Розовый грейпфрут","duft-industry",["grapefruit"],true),p("tiramisu","Tiramisu","Тирамису","duft-industry",["vanilla","pastry","cacao"]),p("goa-mango","Goa Mango","Манго Гоа","duft-industry",["tropical-fruit"]),p("banana-gum","Banana Gum","Банановая жвачка","duft-industry",["banana","candy"]),p("berry","Berry","Ягоды","duft-industry",["berry"]),p("citrus-tea","Citrus Tea","Цитрусовый чай","duft-industry",["citrus","bergamot"],true),p("cola","Cola","Кола","duft-industry",["cola","beverage"]),p("currant","Currant","Смородина","duft-industry",["blackcurrant"],true),p("grape-mint","Grape Mint","Виноград с мятой","duft-industry",["grape","mint"],false,true),p("lemon-cake","Lemon Cake","Лимонный пирог","duft-industry",["lemon","pastry"],true),p("raspberry","Raspberry","Малина","duft-industry",["raspberry"],true),p("vanilla-cream","Vanilla Cream","Ванильный крем","duft-industry",["vanilla","cream"])
  ]}]},
  {slug:"daily-hookah",name:"Daily Hookah",sourceKey:"daily-industry",lines:[{slug:"formula",name:"Formula",strength:"light",sourceKey:"daily-industry",products:[
    p("limonium","Limonium","Лимоний","daily-industry",["lemon","citrus"],true),p("berry-sorbet","Berry Sorbet","Ягодный сорбет","daily-industry",["berry","ice-cream"],true,true),p("cream","Cream","Сливочный крем","daily-industry",["cream"]),p("orangina","Orangina","Оранжина","daily-industry",["orange","beverage"],true),p("grape-jelly","Grape Jelly","Виноградное желе","daily-industry",["grape","coconut"]),p("mint-pastille","Mint Pastille","Мятная пастилка","daily-industry",["mint","candy"],false,true),p("lemon-pie","Lemon Pie","Лимонный пай","daily-industry",["lemon","pastry"],true),p("free-cuba","Free Cuba","Свободная Куба","daily-industry",["cola","lemon","beverage"],true),p("belgian-waffles","Belgian Waffles","Бельгийские вафли","daily-industry",["pastry","cinnamon","cream"]),p("mint-chocolate","Mint Chocolate","Мятный шоколад","daily-industry",["cacao","mint"],false,true),p("tropical-smoothie","Tropical Smoothie","Тропический смузи","daily-industry",["lychee","raspberry","beverage"]),p("horchata","Horchata","Орчата","daily-industry",["beverage","cream","cinnamon"]),p("melonium","Melonium","Дыниум","daily-industry",["tropical-fruit"]),p("pear","Pearium","Грушиум","daily-industry",["tropical-fruit"]),p("blueberry-crumble","Blueberry Crumble","Черничный крамбл","daily-industry",["blueberry","pastry"])
  ]}]},
  {slug:"blackburn",name:"BlackBurn",sourceKey:"blackburn-official",lines:[{slug:"original",name:"Original",strength:"medium",sourceKey:"blackburn-industry",products:[
    p("lemon-shock","Lemon Shock","Лимон Шок","blackburn-industry",["lemon","citrus"],true),p("apple-shock","Apple Shock","Яблоко Шок","blackburn-industry",["apple"],true),p("peach-yoghurt","Peach Yoghurt","Персиковый йогурт","blackburn-industry",["peach","yoghurt"]),p("ice-baby","Ice Baby","Айс Бэйби","blackburn-industry",["berry","grapefruit"],true,true),p("something-tropical","Something Tropical","Something Тропический","blackburn-industry",["tropical-fruit"]),p("lemon-sweets","Lemon Sweets","Лимонные конфеты","blackburn-industry",["lemon","candy"],true),p("chuppa-graper","Chuppa Graper","Чуппа Грейпер","blackburn-industry",["grape","candy"]),p("bapai-dinner","Bapai Dinner","Бапай Диннер","blackburn-industry",["tropical-fruit"]),p("kiwi-stoner","Kiwi Stoner","Киви Стоунер","blackburn-industry",["tropical-fruit"],true),p("green-tea","Green Tea","Зелёный чай","blackburn-industry",["herbal","beverage"]),p("annas-shock","Annas Shock","Ананас Шок","blackburn-industry",["pineapple"],true),p("raspberry","Raspberry","Малина","blackburn-industry",["raspberry"],true),p("blackcurrant","Blackcurrant","Чёрная смородина","blackburn-industry",["blackcurrant"],true),p("mango","Mango","Манго","blackburn-industry",["tropical-fruit"]),p("cola","Cola","Кола","blackburn-industry",["cola","beverage"])
  ]}]}
];
