import type { CatalogSource, SeedBrand, SeedProduct } from "./catalog-v1.js";

export const sourcesV3: CatalogSource[] = [
  {key:"chabacco-official",url:"https://chabacco.ru/product/chabacco",title:"Линейка моно-ароматов Chabacco",publisher:"Chabacco",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Official catalog provides current labels and descriptions."},
  {key:"chabacco-strength",url:"https://chabacco.ru/en",title:"Chabacco products",publisher:"Chabacco",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Official English page confirms Medium and Strong product strengths."},
  {key:"sebero-official",url:"https://seberotobacco.com/",title:"Sebero Hookah Tobacco",publisher:"Sebero",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Official international site confirms brand and current products where indexed."},
  {key:"sebero-industry",url:"https://hookahportal.ru/tobaccos/sebero",title:"Табаки — Sebero",publisher:"Hookah Portal",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"medium",notes:"Fallback for exact Classic assortment because the official catalog is only partially indexed; no commerce data collected."},
  {key:"spectrum-industry",url:"https://hookahportal.ru/tobaccos/spectrum",title:"Табаки — Spectrum",publisher:"Hookah Portal",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"medium",notes:"Industry catalog fallback; manufacturer catalog was not reliably accessible. No commerce data collected."},
  {key:"bonche-official",url:"https://bonche.ru/products",title:"Продукция Bonche",publisher:"Bonche Tobacco",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Official site confirms active cigar-leaf product range, but names are not exposed in indexed text."},
  {key:"bonche-industry",url:"https://hookahportal.ru/tobaccos/bonche",title:"Табаки — Bonche",publisher:"Hookah Portal",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"medium",notes:"Fallback for exact flavor names/facets because official cards are not text-indexed; no commerce data collected."}
];

const p=(slug:string,en:string,ru:string,sourceKey:string,tags:string[],acid=false,fresh=false):SeedProduct=>({slug,nameEn:en,nameRu:ru,sourceKey,tags,translationOrigin:"normalized_translation",sweetness:"pronounced",acidity:acid?"pronounced":"subtle",freshness:fresh?"pronounced":"subtle"});

export const brandsV3: SeedBrand[]=[
 {slug:"chabacco",name:"Chabacco",sourceKey:"chabacco-official",lines:[{slug:"medium",name:"Medium",strength:"medium",sourceKey:"chabacco-strength",products:[
  p("ice-mango","Ice Mango","Айс манго","chabacco-official",["tropical-fruit","mint"],false,true),p("pineapple","Pineapple","Ананас","chabacco-official",["pineapple"],true),p("astrakhan-watermelon","Astrakhan Watermelon","Астраханский арбуз","chabacco-official",["watermelon"]),p("white-wine","White Wine","Белое вино","chabacco-official",["grape","beverage"],true),p("elderberry","Elderberry","Бузина","chabacco-official",["elderberry"],true),p("cherry","Cherry","Вишня","chabacco-official",["cherry"],true),p("grapefruit","Grapefruit","Грейпфрут","chabacco-official",["grapefruit"],true),p("double-apple","Double Apple","Двойное яблоко","chabacco-official",["apple","spices"]),p("wild-cherry","Wild Cherry","Дикая вишня","chabacco-official",["cherry"],true),p("green-apple","Green Apple","Зелёное яблоко","chabacco-official",["apple"],true),p("wild-strawberry","Wild Strawberry","Земляника","chabacco-official",["strawberry"],true),p("cola","Cola","Кола","chabacco-official",["cola","beverage"]),p("sour-lingonberry","Sour Lingonberry","Кислая брусника","chabacco-official",["lingonberry"],true),p("chinese-melon","Chinese Melon","Китайская дыня","chabacco-official",["tropical-fruit"]),p("jasmine-tea","Jasmine Tea","Жасминовый чай","chabacco-official",["herbal","beverage"])
 ]}]},
 {slug:"sebero",name:"Sebero",sourceKey:"sebero-official",lines:[{slug:"classic",name:"Classic",strength:"light",sourceKey:"sebero-industry",products:[
  p("spice-fruit","Spice Fruit","Пряные фрукты","sebero-official",["strawberry","blackcurrant","herbal"],true),p("arctic-melon","Arctic Melon","Арктическая дыня","sebero-industry",["tropical-fruit","mint"],false,true),p("banana","Banana","Банан","sebero-industry",["banana"]),p("blackcurrant","Blackcurrant","Чёрная смородина","sebero-industry",["blackcurrant"],true),p("blueberry","Blueberry","Черника","sebero-industry",["blueberry"],true),p("cherry","Cherry","Вишня","sebero-industry",["cherry"],true),p("cola","Cola","Кола","sebero-industry",["cola","beverage"]),p("grapefruit","Grapefruit","Грейпфрут","sebero-industry",["grapefruit"],true),p("green-apple","Green Apple","Зелёное яблоко","sebero-industry",["apple"],true),p("lemon","Lemon","Лимон","sebero-industry",["lemon"],true),p("mango","Mango","Манго","sebero-industry",["tropical-fruit"]),p("mint","Mint","Мята","sebero-industry",["mint"],false,true),p("passion-fruit","Passion Fruit","Маракуйя","sebero-industry",["passion-fruit"],true),p("raspberry","Raspberry","Малина","sebero-industry",["raspberry"],true),p("watermelon","Watermelon","Арбуз","sebero-industry",["watermelon"])
 ]}]},
 {slug:"spectrum",name:"Spectrum",sourceKey:"spectrum-industry",lines:[{slug:"classic",name:"Classic",strength:"medium",sourceKey:"spectrum-industry",products:[
  p("barberry","Barberry","Барбарис","spectrum-industry",["berry"],true),p("berry-drink","Berry Drink","Ягодный напиток","spectrum-industry",["berry","beverage"],true),p("brazilian-tea","Brazilian Tea","Бразильский чай","spectrum-industry",["herbal","beverage"]),p("caribbean-rum","Caribbean Rum","Карибский ром","spectrum-industry",["beverage"]),p("citrus-mix","Citrus Mix","Цитрусовый микс","spectrum-industry",["citrus","orange","lemon"],true),p("cookies-milk","Cookies & Milk","Печенье с молоком","spectrum-industry",["pastry","cream"]),p("currant-crush","Currant Crush","Смородиновый краш","spectrum-industry",["blackcurrant"],true),p("energy-storm","Energy Storm","Энергетик","spectrum-industry",["beverage","citrus"],true),p("fire-wine","Fire Wine","Пряное вино","spectrum-industry",["grape","beverage","spices"]),p("green-pop","Green Pop","Зелёный леденец","spectrum-industry",["apple","candy"],true),p("honey-comb","Honey Comb","Медовые соты","spectrum-industry",["honey"]),p("lemon-hurricane","Lemon Hurricane","Лимонный ураган","spectrum-industry",["lemon","citrus"],true),p("morning-mango","Morning Mango","Утренний манго","spectrum-industry",["tropical-fruit"]),p("nutter","Nutter","Ореховый десерт","spectrum-industry",["pecan","pastry"]),p("russian-raspberry","Russian Raspberry","Русская малина","spectrum-industry",["raspberry"],true)
 ]}]},
 {slug:"bonche",name:"Bonche",sourceKey:"bonche-official",lines:[{slug:"cigar",name:"Cigar",strength:"strong",sourceKey:"bonche-official",products:[
  p("apple-strudel","Apple Strudel","Яблочный штрудель","bonche-industry",["apple","pastry","cinnamon"]),p("banana","Banana","Банан","bonche-industry",["banana"]),p("barberry","Barberry","Барбарис","bonche-industry",["berry"],true),p("bergamot","Bergamot","Бергамот","bonche-industry",["bergamot","herbal"]),p("blackcurrant","Blackcurrant","Чёрная смородина","bonche-industry",["blackcurrant"],true),p("cherry","Cherry","Вишня","bonche-industry",["cherry"],true),p("chocolate","Chocolate","Шоколад","bonche-industry",["cacao"]),p("coconut","Coconut","Кокос","bonche-industry",["coconut"]),p("coffee","Coffee","Кофе","bonche-industry",["beverage"]),p("grapefruit","Grapefruit","Грейпфрут","bonche-industry",["grapefruit"],true),p("lemon","Lemon","Лимон","bonche-industry",["lemon"],true),p("mango","Mango","Манго","bonche-industry",["tropical-fruit"]),p("pear","Pear","Груша","bonche-industry",["tropical-fruit"]),p("raspberry","Raspberry","Малина","bonche-industry",["raspberry"],true),p("vanilla","Vanilla","Ваниль","bonche-industry",["vanilla"])
 ]}]}
];
