import type { SeedBrand, SeedProduct } from "./catalog-v1.js";

const p=(slug:string,en:string,ru:string,tags:string[]):SeedProduct=>({slug,nameEn:en,nameRu:ru,sourceKey:"musthave-catalog",tags,translationOrigin:"normalized_translation",sweetness:"pronounced",acidity:"subtle",freshness:"subtle"});

// Products required by accepted recipe sources. Kept separate from catalog-v1 so
// the original artifact remains immutable; importer natural keys merge this extension.
export const mixSupportBrands: SeedBrand[]=[{slug:"musthave",name:"MUSTHAVE",sourceKey:"musthave-catalog",lines:[{slug:"original",name:"Original",strength:"medium",sourceKey:"musthave-catalog",products:[
 p("berry-holls","Berry Holls","Ягодные леденцы",["berry","candy"]),p("raspberry","Raspberry","Малина",["raspberry"]),p("orange-team","Orange Team","Апельсин и мандарин",["orange","citrus"]),p("blackberry","Blackberry","Ежевика",["blackberry"]),p("cheesecake","Cheesecake","Чизкейк",["pastry","cream"]),p("kiwi-smoothie","Kiwi Smoothie","Киви-смузи",["tropical-fruit","beverage"]),p("caribbean-rum","Caribbean Rum","Карибский ром",["beverage"]),p("green-fizz","Green Fizz","Киви, кактус и абсент",["tropical-fruit","herbal"]),p("ice-mint","Ice Mint","Освежающая мята",["mint"]),p("black-currant","Black Currant","Чёрная смородина",["blackcurrant"]),p("blueberry","Blueberry","Черника",["blueberry"]),p("forest-berries","Forest Berries","Лесные ягоды",["berry"]),p("estragon","Estragon","Эстрагон",["herbal"]),p("pineapple-rings","Pineapple Rings","Ананасовые колечки",["pineapple","candy"]),p("sweet-peach","Sweet Peach","Персик",["peach"]),p("apple-drops","Apple Drops","Яблочные леденцы",["apple","candy"]),p("mango-sling","Mango Sling","Манго-слинг",["tropical-fruit","beverage"]),p("mad-pear","Mad Pear","Груша",["tropical-fruit"]),p("cookie","Cookie","Шоколадное печенье",["cacao","pastry"]),p("baikal","Baikal","Лесные травы и хвоя",["fir","herbal"]),p("lemon-lime","Lemon-Lime","Лимон и лайм",["lemon","citrus"]),p("pinkman","Pinkman","Пинкман",["berry","citrus"]),p("coconut-shake","Coconut Shake","Кокосовый шейк",["coconut","cream"]),p("marula","Marula","Марула",["tropical-fruit"]),p("grapefruit","Grapefruit","Грейпфрут",["grapefruit"]),p("nord-star","Nord Star","Кислая вишня",["cherry"]),p("masala-tea","Masala Tea","Чай масала",["beverage","spices"]),p("frosty","Frosty","Охлаждающий",["mint"]),p("melonade","Melonade","Мелонад",["watermelon","tropical-fruit"]),p("feijoa","Feijoa","Фейхоа",["feijoa"]),p("cranberry","Cranberry","Клюква",["cranberry"]),p("pistachio","Pistachio","Фисташка",["pecan"]),p("citrus-spritz","Citrus Spritz","Цитрусовый коктейль",["citrus","beverage"]),p("banana-mama","Banana Mama","Банан",["banana"]),p("barberry-candy","Barberry Candy","Барбарисовые конфеты",["berry","candy"])
]}]}];
