// Generated by npm run catalog:refresh:darkside. Commerce, availability and media fields intentionally excluded.
import type { DarksideSnapshot } from "../src/darksideRefresh.js";
export const darksideSnapshot:DarksideSnapshot={
  "source": {
    "pageUrl": "https://darkside-world.com/products/brand/darkside",
    "catalogUrl": "https://darkside-world.com/products/catalog",
    "apiUrl": "https://tmp.zmek.org/mixbck/ext_api/v1/flavors",
    "brandId": "64077e63d3e3abe4a6ce3d6a",
    "accessedAt": "2026-09-10",
    "verifiedAt": "2026-09-10",
    "publisher": "DARKSIDE"
  },
  "products": [
    {
      "uid": "64077e63d3e3abe4a6ce3d92",
      "slug": "admiral-acbar",
      "title": "ADMIRAL ACBAR",
      "descriptionRu": "Сливочный вкус сладкой овсяной каши с ягодами.",
      "officialTags": [
        "десертный",
        "овсяная_каша",
        "сладкий",
        "ягодный"
      ],
      "officialCategories": [
        "Десерты"
      ],
      "tags": [
        "pastry",
        "oatmeal",
        "sweet",
        "berry"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d93",
      "slug": "bananapapa",
      "title": "BANANAPAPA",
      "descriptionRu": "Яркий и насыщенный вкус спелого сладкого банана.",
      "officialTags": [
        "банан"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "banana"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d9c",
      "slug": "barvy-citrus",
      "title": "BARVY CITRUS",
      "descriptionRu": "Освежающий аромат в цитрусовом миксе апельсина, лимона и грейпфрута.",
      "officialTags": [
        "апельсин",
        "грейпфрут",
        "лимон"
      ],
      "officialCategories": [
        "Напиток"
      ],
      "tags": [
        "orange",
        "grapefruit",
        "lemon"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d99",
      "slug": "barvy-orange",
      "title": "BARVY ORANGE",
      "descriptionRu": "Яркий летний аромат освежающего апельсинового фреша.",
      "officialTags": [
        "апельсиновый_сок"
      ],
      "officialCategories": [
        "Цитрусы"
      ],
      "tags": [
        "orange",
        "beverage"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d94",
      "slug": "basil-blast",
      "title": "BASIL BLAST",
      "descriptionRu": "Свежий вкус душистого зеленого базилика.",
      "officialTags": [
        "базилик"
      ],
      "officialCategories": [
        "Травы"
      ],
      "tags": [
        "basil"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d9d",
      "slug": "bassberry",
      "title": "BASSBERRY",
      "descriptionRu": "Насыщенный сладкий вкус ягод бузины с цветочными нотками.",
      "officialTags": [
        "бузина"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "elderberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d95",
      "slug": "bergamonstr",
      "title": "BERGAMONSTR",
      "descriptionRu": "Пряный и слегка терпкий вкус спелого бергамота.",
      "officialTags": [
        "бергамот"
      ],
      "officialCategories": [
        "Травы"
      ],
      "tags": [
        "bergamot"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d96",
      "slug": "blackberry",
      "title": "BLACKBERRY",
      "descriptionRu": "Сладкий аромат свежесобранной ежевики.",
      "officialTags": [
        "ежевика"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "blackberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d9a",
      "slug": "blackcurrant",
      "title": "BLACKCURRANT",
      "descriptionRu": "Терпкий аромат спелых ягод черной смородины.",
      "officialTags": [
        "черная_смородина"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "blackcurrant"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "6638ba7f0b9a126e9a179508",
      "slug": "blackout",
      "title": "BLACKOUT",
      "descriptionRu": "Накрывающая с головой сладость сливочного мороженого с послевкусием спелого банана.",
      "officialTags": [
        "банан",
        "лимитка",
        "мороженое"
      ],
      "officialCategories": [
        "Десерты"
      ],
      "tags": [
        "banana",
        "ice-cream"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "68da4da846ea644192351fa4",
      "slug": "bloody-orange",
      "title": "BLOODY ORANGE",
      "descriptionRu": "Кисло-сладкий аромат мякоти красного сицилийского апельсина.",
      "officialTags": [
        "красный_апельсин"
      ],
      "officialCategories": [
        "Цитрусы"
      ],
      "tags": [
        "orange"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "6a3a3897cad7d389b9b24fed",
      "slug": "blueberry-blast-2-0",
      "title": "BLUEBERRY BLAST 2.0",
      "descriptionRu": "Аромат сладких ягод черники с легкой кислой ноткой.",
      "officialTags": [
        "черника",
        "ягода"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "blueberry",
        "berry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d98",
      "slug": "bounty-hunter",
      "title": "BOUNTY HUNTER",
      "descriptionRu": "Нежный, слегка сливочный вкус тропического кокоса.",
      "officialTags": [
        "кокос"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "coconut"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d9b",
      "slug": "breaking-red",
      "title": "BREAKING RED",
      "descriptionRu": "Яркий вкус сладкого граната с легкой кислинкой.",
      "officialTags": [
        "гранат"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "pomegranate"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64f59862888754c55eed5dae",
      "slug": "cream-soda",
      "title": "C.R.E.A.M. S.O.D.A.",
      "descriptionRu": "Сладкий, слегка освежающий аромат сливочной газировки с ноткой ванили.",
      "officialTags": [
        "ваниль",
        "крем-сода"
      ],
      "officialCategories": [
        "Десерты",
        "Напиток"
      ],
      "tags": [
        "vanilla",
        "cream-soda"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da1",
      "slug": "cherry-rocks",
      "title": "CHERRY ROCKS",
      "descriptionRu": "Насыщенный вкус вишневых леденцов с ярко выраженным кислым послевкусием.",
      "officialTags": [
        "вишневые_леденцы"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "cherry",
        "candy"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da0",
      "slug": "code-cherry",
      "title": "CODE CHERRY",
      "descriptionRu": "Насыщенный вкус спелой вишни с терпким послевкусием косточки.",
      "officialTags": [
        "вишня"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "cherry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3d9e",
      "slug": "cosmo-flower",
      "title": "COSMO FLOWER",
      "descriptionRu": "Яркий цветочный аромат с ягодным послевкусием.",
      "officialTags": [
        "сирень",
        "черника"
      ],
      "officialCategories": [
        "Травы",
        "Ягоды"
      ],
      "tags": [
        "lilac",
        "blueberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da2",
      "slug": "cosmos",
      "title": "COSMOS",
      "descriptionRu": "Знаменитый вкус классического коктейля с добавлением цитрусового ликера и клюквенного морса.",
      "officialTags": [
        "клюква",
        "ликер",
        "цитрус"
      ],
      "officialCategories": [
        "Алкоголь"
      ],
      "tags": [
        "cranberry",
        "liqueur",
        "citrus"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "65c092fac15044e0da16ce44",
      "slug": "crystal-grape",
      "title": "CRYSTAL GRAPE",
      "descriptionRu": "Cладкий, слегка освежающий аромат спелого белого винограда.",
      "officialTags": [
        "белый_виноград"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "grape"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da3",
      "slug": "cyber-kiwi",
      "title": "CYBER KIWI",
      "descriptionRu": "Яркий вкус сладкого смузи из спелых плодов киви с кислыми нотками.",
      "officialTags": [
        "киви",
        "смузи"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "kiwi",
        "smoothie"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da4",
      "slug": "dark-icecream",
      "title": "DARK ICECREAM",
      "descriptionRu": "Мягкий вкус сливочного мороженого с шоколадной крошкой",
      "officialTags": [
        "десертный",
        "мороженое",
        "свежий",
        "сладкий",
        "шоколад"
      ],
      "officialCategories": [
        "Десерты"
      ],
      "tags": [
        "pastry",
        "ice-cream",
        "cooling",
        "sweet",
        "cacao"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da5",
      "slug": "dark-mint",
      "title": "DARK MINT",
      "descriptionRu": "Насыщенный освежающий вкус сладкой перечной мяты",
      "officialTags": [
        "перечная_мята"
      ],
      "officialCategories": [
        "Травы"
      ],
      "tags": [
        "mint"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dab",
      "slug": "dark-passion",
      "title": "DARK PASSION",
      "descriptionRu": "Вкус кисло-сладкой маракуйи с тонкими терпкими нотками",
      "officialTags": [
        "маракуйя"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "passion-fruit"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da6",
      "slug": "darkside-cola",
      "title": "DARKSIDE COLA",
      "descriptionRu": "Бодрящий освежающий вкус колы с долькой лимона.",
      "officialTags": [
        "кола",
        "лимон"
      ],
      "officialCategories": [
        "Напиток",
        "Цитрусы"
      ],
      "tags": [
        "cola",
        "lemon"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da8",
      "slug": "darksupra",
      "title": "DARKSUPRA",
      "descriptionRu": "Вкус традиционного японского зеленого чая Сенча с тонкой ноткой жасмина.",
      "officialTags": [
        "жасмин",
        "зеленый_чай"
      ],
      "officialCategories": [
        "Напиток",
        "Пряности",
        "Травы"
      ],
      "tags": [
        "jasmine",
        "tea"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3da9",
      "slug": "deep-blue-sea",
      "title": "DEEP BLUE SEA",
      "descriptionRu": "Нежный вкус традиционного сахарного печенья со сливочными нотками",
      "officialTags": [
        "десертный",
        "печенье",
        "сладкий",
        "сливки"
      ],
      "officialCategories": [
        "Десерты"
      ],
      "tags": [
        "pastry",
        "cookie",
        "sweet",
        "cream"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3daa",
      "slug": "desert-eagle",
      "title": "DESERT EAGLE",
      "descriptionRu": "Сладкий аромат кактуса с терпким послевкусием.",
      "officialTags": [
        "кактус"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "cactus"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "642997a0b845831a7b6212d2",
      "slug": "deus",
      "title": "DEUS",
      "descriptionRu": "Аромат односолодового островного виски с ярко выраженным дымным оттенком.",
      "officialTags": [
        "алкоголь",
        "виски",
        "лимитка",
        "пряный"
      ],
      "officialCategories": [
        "Алкоголь"
      ],
      "tags": [
        "alcohol",
        "whiskey",
        "spices"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dae",
      "slug": "falling-star",
      "title": "FALLING STAR",
      "descriptionRu": "Вкус сладкого манго с освежающей маракуйей в тропическом коктейле.",
      "officialTags": [
        "манго",
        "маракуйя"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "mango",
        "passion-fruit"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "6a50e3516e0c7c74cd6446dc",
      "slug": "forever-young",
      "title": "FOREVER YOUNG",
      "descriptionRu": "Аромат вишневого алкогольного напитка Blazer, ставшего символом целой эпохи.",
      "officialTags": [
        "вишневый_блейзер",
        "лимитка"
      ],
      "officialCategories": [
        "Алкоголь"
      ],
      "tags": [
        "cherry",
        "beverage"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3daf",
      "slug": "fruittallity",
      "title": "FRUITTALLITY",
      "descriptionRu": "Вкус сладких жевательных конфет с соком лесных ягод.",
      "officialTags": [
        "лесные_ягоды",
        "сливки"
      ],
      "officialCategories": [
        "Десерты",
        "Ягоды"
      ],
      "tags": [
        "berry",
        "cream"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db0",
      "slug": "generis-raspberry",
      "title": "GENERIS RASPBERRY",
      "descriptionRu": "Нежный сладкий аромат спелых ягод малины.",
      "officialTags": [
        "малина"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "raspberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db3",
      "slug": "glitch-ice-tea",
      "title": "GLITCH ICE TEA",
      "descriptionRu": "Освежающий вкус прохладного персикового чая.",
      "officialTags": [
        "персик",
        "чай"
      ],
      "officialCategories": [
        "Напиток"
      ],
      "tags": [
        "peach",
        "tea"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db6",
      "slug": "goal",
      "title": "GOAL",
      "descriptionRu": "Насыщенный вкус сладкого черничного энергетика с легкой свежестью.",
      "officialTags": [
        "черника",
        "энергетик"
      ],
      "officialCategories": [
        "Напиток"
      ],
      "tags": [
        "blueberry",
        "energy-drink"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db1",
      "slug": "grape-core",
      "title": "GRAPE CORE",
      "descriptionRu": "Богатый вкус мякоти спелого винограда.",
      "officialTags": [
        "виноград"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "grape"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db2",
      "slug": "green-beam",
      "title": "GREEN BEAM",
      "descriptionRu": "В меру сладкий, мягкий и чуть вяжущий вкус плодов фейхоа.",
      "officialTags": [
        "фейхоа"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "feijoa"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db5",
      "slug": "green-mist",
      "title": "GREEN MIST",
      "descriptionRu": "Свежий цитрусовый коктейль с алкогольной ноткой",
      "officialTags": [
        "алкоголь",
        "кислый",
        "пряный",
        "цитрусовый"
      ],
      "officialCategories": [
        "Алкоголь"
      ],
      "tags": [
        "alcohol",
        "sour",
        "spices",
        "citrus"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db4",
      "slug": "guava-rebel",
      "title": "GUAVA REBEL",
      "descriptionRu": "Насыщенный вкус сочной мякоти гуавы со слегка терпким оттенком",
      "officialTags": [
        "гуава",
        "свежий",
        "сладкий",
        "травянистый",
        "фруктовый"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "guava",
        "cooling",
        "sweet",
        "herbal",
        "fruit"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db7",
      "slug": "honey-dust",
      "title": "HONEY DUST",
      "descriptionRu": "Сладкий вкус натурального цветочного меда с тонкими терпкими нотками",
      "officialTags": [
        "десертный",
        "мед",
        "пряный",
        "сладкий"
      ],
      "officialCategories": [
        "Гастрономия"
      ],
      "tags": [
        "pastry",
        "honey",
        "spices",
        "sweet"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db8",
      "slug": "ice-granny",
      "title": "ICE GRANNY",
      "descriptionRu": "Насыщенный вкус спелого зеленого яблока Гренни Смит.",
      "officialTags": [
        "зеленое_яблоко"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "apple"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dba",
      "slug": "kalee-grapefruit-2",
      "title": "KALEE GRAPEFRUIT 2.0",
      "descriptionRu": "Кисло сладкий аромат грейпфрута с терпким послевкусием",
      "officialTags": [
        "грейпфрут"
      ],
      "officialCategories": [
        "Цитрусы"
      ],
      "tags": [
        "grapefruit"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "66a7521e0b9a126e9a419508",
      "slug": "kashmir-goa-java",
      "title": "KASHMIR GOA JAVA",
      "descriptionRu": "Терпкий аромат гуавы с выраженным послевкусием индийских специй. Такой же эпичный, как болливудские спецэффекты!",
      "officialTags": [
        "гуава",
        "кашмир",
        "лимитка"
      ],
      "officialCategories": [
        "Пряности"
      ],
      "tags": [
        "guava",
        "spices"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3db9",
      "slug": "killer-milk",
      "title": "KILLER MILK",
      "descriptionRu": "Насыщенный сладкий вкус сгущенного молока.",
      "officialTags": [
        "сгущенное_молоко"
      ],
      "officialCategories": [
        "Десерты"
      ],
      "tags": [
        "condensed-milk"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dbb",
      "slug": "lemonblast",
      "title": "LEMONBLAST",
      "descriptionRu": "Освежающий кислый аромат спелого лимона с легкой горчинкой.",
      "officialTags": [
        "лимон"
      ],
      "officialCategories": [
        "Цитрусы"
      ],
      "tags": [
        "lemon"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dbc",
      "slug": "mango-lassi-2-0",
      "title": "MANGO LASSI 2.0",
      "descriptionRu": "Яркий, сладкий аромат густого шейка из мякоти спелого манго.",
      "officialTags": [
        "манго"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "mango"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "68beaf00a8411f347b602e7a",
      "slug": "mary-jane-2-0",
      "title": "MARY JANE 2.0",
      "descriptionRu": "Тот самый травянистый аромат, который ни с чем не перепутать.",
      "officialTags": [
        "лимитка",
        "сладкий",
        "травянистый"
      ],
      "officialCategories": [
        "Травы"
      ],
      "tags": [
        "sweet",
        "herbal"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dbe",
      "slug": "needls",
      "title": "NEEDLS",
      "descriptionRu": "Свежий хвойный аромат с легкой горечью и смолистым оттенком.",
      "officialTags": [
        "хвоя"
      ],
      "officialCategories": [
        "Травы"
      ],
      "tags": [
        "fir"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dbf",
      "slug": "nordberry",
      "title": "NØRDBERRY",
      "descriptionRu": "Охлажденный кисло-сладкий морс из ягод клюквы.",
      "officialTags": [
        "клюквенный_морс"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "cranberry",
        "beverage"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc1",
      "slug": "pear",
      "title": "PEAR",
      "descriptionRu": "Насыщенный аромат сладкого грушевого лимонада.",
      "officialTags": [
        "груша",
        "лимонад"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "pear",
        "lemonade"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc2",
      "slug": "pineapple-pulse",
      "title": "PINEAPPLE PULSE",
      "descriptionRu": "Сладкий вкус мякоти ананаса с легким кислым послевкусием.",
      "officialTags": [
        "ананас"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "pineapple"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "65e58d0eef9e870717f1cd9d",
      "slug": "pomelow",
      "title": "POMELOW",
      "descriptionRu": "Насыщенный аромат сладкого помело с характерной терпкой ноткой.",
      "officialTags": [
        "помело"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "pomelo"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc7",
      "slug": "raf-in-the-jungle",
      "title": "RAF IN THE JUNGLE",
      "descriptionRu": "Мягкий сливочно-шоколадный вкус кофе RAF с апельсиновой цедрой",
      "officialTags": [
        "апельсин",
        "десертный",
        "кофе",
        "напиток",
        "пряный",
        "сладкий",
        "шоколад"
      ],
      "officialCategories": [],
      "tags": [
        "orange",
        "pastry",
        "coffee",
        "beverage",
        "spices",
        "sweet",
        "cacao"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc5",
      "slug": "red-alert",
      "title": "RED ALERT",
      "descriptionRu": "Сочная мякоть арбуза с нотками медовой дыни в освежающем безалкогольном напитке.",
      "officialTags": [
        "арбуз",
        "дыня"
      ],
      "officialCategories": [
        "Фрукты",
        "Ягоды"
      ],
      "tags": [
        "watermelon",
        "melon"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc6",
      "slug": "red-rush",
      "title": "RED RUSH",
      "descriptionRu": "Насыщенный сладкий вкус барбарисовых конфет.",
      "officialTags": [
        "барбарисовые_леденцы"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "candy"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc3",
      "slug": "red-tea",
      "title": "RED TEA",
      "descriptionRu": "Пряный аромат крепкого красного чая каркаде.",
      "officialTags": [
        "красный_чай"
      ],
      "officialCategories": [
        "Напиток"
      ],
      "tags": [
        "tea"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64cfad140ff8297818cbf809",
      "slug": "red-zeppelin",
      "title": "RED ZEPPELIN",
      "descriptionRu": "Насыщенный сладкий аромат ягод крыжовника с легким терпким оттенком.",
      "officialTags": [
        "крыжовник",
        "сладкий",
        "ягодный"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "gooseberry",
        "sweet",
        "berry"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc4",
      "slug": "redberry",
      "title": "REDBERRY",
      "descriptionRu": "Яркий аромат спелой грозди красной смородины с кислинкой.",
      "officialTags": [
        "красная_смородина"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "redcurrant"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "68839a0e614a85b5f00df9f2",
      "slug": "retro-apple",
      "title": "RETRO APPLE",
      "descriptionRu": "Сладкий аромат спелого красного яблока.",
      "officialTags": [
        "красное_яблоко"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "apple"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dcd",
      "slug": "salbei",
      "title": "SALBEI",
      "descriptionRu": "Терпкий, травянистый аромат свежих листьев шалфея.",
      "officialTags": [
        "освежающий",
        "пряный",
        "свежий",
        "травянистый",
        "шалфей"
      ],
      "officialCategories": [
        "Травы"
      ],
      "tags": [
        "cooling",
        "spices",
        "herbal",
        "sage"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dcf",
      "slug": "space-jam",
      "title": "SPACE JAM",
      "descriptionRu": "Насыщенный вкус ягод клубники в сладком сиропе.",
      "officialTags": [
        "клубничный_джем"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "strawberry",
        "jam"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "684ff9b897b9fb904e74a32a",
      "slug": "starlime",
      "title": "STARLIME",
      "descriptionRu": "Кисло-сладкий, слегка освежающий аромат спелого лайма",
      "officialTags": [
        "лайм"
      ],
      "officialCategories": [
        "Цитрусы"
      ],
      "tags": [
        "lime"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dca",
      "slug": "strawberry-light",
      "title": "STRAWBERRY LIGHT",
      "descriptionRu": "Нежный, сладкий аромат спелой садовой клубники.",
      "officialTags": [
        "клубника"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "strawberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "6666e58e0b9a126e9a2c78b5",
      "slug": "supermint",
      "title": "SUPERMINT",
      "descriptionRu": "Освежающий ментоловый аромат с ярким послевкусием сладкой мяты.",
      "officialTags": [
        "мята"
      ],
      "officialCategories": [
        "Холод"
      ],
      "tags": [
        "mint"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dcb",
      "slug": "supernova",
      "title": "SUPERNOVA",
      "descriptionRu": "Захватывающий дух, леденящий ментоловый холод.",
      "officialTags": [
        "ментол"
      ],
      "officialCategories": [
        "Холод"
      ],
      "tags": [
        "cooling"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dc9",
      "slug": "sweet-comet",
      "title": "SWEET COMET",
      "descriptionRu": "Освежающий аромат спелой клюквы с ноткой банана.",
      "officialTags": [
        "банан",
        "клюква"
      ],
      "officialCategories": [
        "Фрукты"
      ],
      "tags": [
        "banana",
        "cranberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "68063b0d54e1570ff5c69a92",
      "slug": "top-gum",
      "title": "TOP GUM",
      "descriptionRu": "Сладкий аромат жевательной резинки со вкусом клубники и арбуза и легким послевкусием дыни.",
      "officialTags": [
        "жвачка",
        "ягоды"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "bubblegum",
        "berry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dd0",
      "slug": "torpedo",
      "title": "TORPEDO",
      "descriptionRu": "Сладкий, но освежающий классический аромат спелой дыни и арбуза.",
      "officialTags": [
        "арбуз",
        "дыня"
      ],
      "officialCategories": [
        "Фрукты",
        "Ягоды"
      ],
      "tags": [
        "watermelon",
        "melon"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dd1",
      "slug": "tropic-ray",
      "title": "TROPIC RAY",
      "descriptionRu": "Карибский коктейль из тропических фруктов на основе кокоса и ананаса.",
      "officialTags": [
        "ананас",
        "кокос",
        "тропические_фрукты"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "pineapple",
        "coconut",
        "tropical-fruit"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dd2",
      "slug": "virgin-melon",
      "title": "VIRGIN MELON",
      "descriptionRu": "Богатый вкус нежной мякоти сочной сахарной дыни",
      "officialTags": [
        "дыня",
        "сладкий",
        "фруктовый"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "melon",
        "sweet",
        "fruit"
      ],
      "strength": "medium",
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dd3",
      "slug": "virgin-peach-2-0",
      "title": "VIRGIN PEACH 2.0",
      "descriptionRu": "Насыщенный сладкий аромат мякоти персика.",
      "officialTags": [
        "персик"
      ],
      "officialCategories": [
        "Тропики"
      ],
      "tags": [
        "peach"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "644f9cbcb905de05a5afa652",
      "slug": "waffle-shuffle",
      "title": "WAFFLE SHUFFLE",
      "descriptionRu": "Аромат хрустящих вафель со сливочным оттенком",
      "officialTags": [
        "вафли",
        "лимон"
      ],
      "officialCategories": [
        "Десерты"
      ],
      "tags": [
        "waffle",
        "lemon"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dd5",
      "slug": "wild-forest",
      "title": "WILD FOREST",
      "descriptionRu": "Насыщенный вкус земляники в сочном коктейле из лесных ягод.",
      "officialTags": [
        "земляника",
        "лесные_ягоды"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "strawberry",
        "berry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "64077e63d3e3abe4a6ce3dd4",
      "slug": "wildberry",
      "title": "WILDBERRY",
      "descriptionRu": "Глубокий душистый аромат свежесобранных лесных ягод.",
      "officialTags": [
        "лесные_ягоды"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "berry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "68f602f96ac4e451cd881616",
      "slug": "yagoda-malina",
      "title": "YAGODA MALINA",
      "descriptionRu": "Аромат сладких ягод малины с легкой кислой ноткой.",
      "officialTags": [
        "малина"
      ],
      "officialCategories": [
        "Ягоды"
      ],
      "tags": [
        "raspberry"
      ],
      "strength": "medium",
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    }
  ]
};
