import type { CatalogSource, Confidence, TranslationOrigin } from "./catalog-v1.js";

export interface MixComponentSeed { product: string; percentage: number }
export interface OfficialMixSeed { slug:string; titleRu:string; titleEn:string; summaryRu:string; summaryEn:string; translationOrigin:TranslationOrigin; sourceKey:string; components:MixComponentSeed[] }

const source=(id:string,title:string,publisher:string):CatalogSource=>{const editorial=publisher==="MUSTHAVE";return {key:`musthave-mix-${id}`,url:`https://musthave.ru/showmixes/view/${id}/`,title,publisher:"MUSTHAVE",author:editorial?undefined:publisher.replace(" / MUSTHAVE",""),sourceType:editorial?"editorial_recipe":"user_recipe",percentageEvidence:"explicit_numeric_percentages",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high" as Confidence,notes:"Hosted recipe page explicitly prints a numeric % beside every component; commerce fields ignored."}};
export const mixSourcesV1:CatalogSource[]=[
 source("434","Насыщенный микс","MUSTHAVE"),source("1133","Потрясающий микс","Александр Демедюк / MUSTHAVE"),source("1215","Микс Лайт","Анжелика Травникова / MUSTHAVE"),source("120","Свежий ягодный микс","Никита Вовченко / MUSTHAVE"),source("682","Микс мастхэвмикм #682","Евгений Высоцкий / MUSTHAVE"),source("702","Микс со 100% статистикой #702","Миша Ананенко / MUSTHAVE"),source("1116","Планакеш","Мартин Космос / MUSTHAVE"),source("700","Приятный микс #700","Александр Муравьев / MUSTHAVE"),source("457","Пушечная свежая миксуля #457","Макс Артамонов / MUSTHAVE"),source("103","Десертос-бомбичес","MUSTHAVE"),source("1192","Коктейль Свобода","Кирилл Тараканов / MUSTHAVE"),source("431","Приятный микс #431","MUSTHAVE"),source("121","Микс от Роберта","Роберт Иванов / MUSTHAVE"),source("911","Потрясающий микс #911","Евгений Мотозюк / MUSTHAVE"),source("567","Брутальный микс #567","MUSTHAVE"),source("1485","Новогодний микс","Наталья Молодых / MUSTHAVE"),source("648","Кокосовая коровка #648","Махмуд Исмаилов / MUSTHAVE"),source("581","Неповторимый микс #581","Ольга Митлина / MUSTHAVE"),source("467","Мелонадный микс #467","MUSTHAVE"),source("809","Кисло-сладенький микс #809","Blvck Jvck / MUSTHAVE")
];
const c=(slug:string,percentage:number):MixComponentSeed=>({product:`musthave/original/${slug}`,percentage});
const m=(id:string,slug:string,ru:string,en:string,summaryRu:string,summaryEn:string,components:MixComponentSeed[]):OfficialMixSeed=>({slug,titleRu:ru,titleEn:en,summaryRu,summaryEn,translationOrigin:"normalized_translation",sourceKey:`musthave-mix-${id}`,components});
export const officialMixesV1:OfficialMixSeed[]=[
 m("434","rich-berry-citrus","Насыщенный микс","Rich Berry Citrus","Ягодные леденцы с малиной и цитрусом.","Berry candy with raspberry and citrus.",[c("berry-holls",50),c("raspberry",30),c("orange-team",20)]),
 m("1133","blackberry-cheesecake-kiwi","Потрясающий микс","Blackberry Cheesecake Kiwi","Ежевика, чизкейк и киви-смузи.","Blackberry, cheesecake, and kiwi smoothie.",[c("blackberry",50),c("cheesecake",30),c("kiwi-smoothie",20)]),
 m("1215","light-rum-fizz","Микс Лайт","Light Rum Fizz","Ром с зелёным фризом и мятой.","Rum with green fizz and mint.",[c("caribbean-rum",50),c("green-fizz",30),c("ice-mint",20)]),
 m("120","fresh-berry-trio","Свежий ягодный микс","Fresh Berry Trio","Три тёмные ягоды в одном миксе.","Three dark berries in one mix.",[c("black-currant",50),c("blueberry",30),c("blackberry",20)]),
 m("682","forest-estragon-candy","Лесные ягоды и эстрагон","Forest Berry Estragon","Лесные ягоды, эстрагон и ягодные леденцы.","Forest berries, estragon, and berry candy.",[c("forest-berries",50),c("estragon",30),c("berry-holls",20)]),
 m("702","pineapple-peach-candy","Ананас, персик и яблочные леденцы","Pineapple Peach Candy","Фруктовый микс с яблочной конфетой.","A fruit mix with apple candy.",[c("pineapple-rings",50),c("sweet-peach",30),c("apple-drops",20)]),
 m("1116","planakesh","Планакеш","Planakesh","Манго, персик и груша.","Mango, peach, and pear.",[c("mango-sling",50),c("sweet-peach",30),c("mad-pear",20)]),
 m("700","orange-cookie-forest","Апельсиновое печенье с хвоей","Orange Cookie Forest","Цитрус, шоколадное печенье и лесные травы.","Citrus, chocolate cookie, and forest herbs.",[c("orange-team",50),c("cookie",30),c("baikal",20)]),
 m("457","fresh-kiwi-berry","Свежий киви с ягодами","Fresh Kiwi Berry","Киви-смузи, лимон-лайм и ягодные леденцы.","Kiwi smoothie, lemon-lime, and berry candy.",[c("kiwi-smoothie",50),c("lemon-lime",30),c("berry-holls",20)]),
 m("103","space-cookie-candy","Космическое печенье","Space Cookie Candy","Тропический Space Flavour с ягодной конфетой и печеньем.","Tropical Space Flavour with berry candy and cookie.",[c("space-flavour",40),c("berry-holls",30),c("cookie",30)]),
 m("1192","freedom-cocktail","Коктейль «Свобода»","Freedom Cocktail","Ягодные леденцы, смородина и цитрусовый спритц.","Berry candy, blackcurrant, and citrus spritz.",[c("berry-holls",40),c("black-currant",30),c("citrus-spritz",30)]),
 m("431","marula-grapefruit-cherry","Марула, грейпфрут и вишня","Marula Grapefruit Cherry","Кисло-сладкий фруктово-цитрусовый микс.","A sweet-and-sour fruit and citrus mix.",[c("marula",40),c("grapefruit",30),c("nord-star",30)]),
 m("121","roberts-banana-candy","Банановый микс Роберта","Robert's Banana Candy","Банан с барбарисовыми, яблочными и ягодными конфетами.","Banana with barberry, apple, and berry candy.",[c("barberry-candy",40),c("banana-mama",30),c("apple-drops",20),c("berry-holls",10)]),
 m("911","soft-pineapple-berries","Ананас с лесными ягодами","Pineapple Forest Berries","Лимон-лайм, лесные ягоды и ананас.","Lemon-lime, forest berries, and pineapple.",[c("lemon-lime",40),c("forest-berries",30),c("pineapple-rings",30)]),
 m("567","brutal-masala-citrus","Брутальный масала-цитрус","Brutal Masala Citrus","Масала, лимон-лайм и апельсин-мандарин.","Masala, lemon-lime, and orange-mandarin.",[c("masala-tea",40),c("lemon-lime",30),c("orange-team",30)]),
 m("1485","new-year-citrus-forest","Новогодний микс","New Year Mix","Грейпфрут, персик и хвойный лес.","Grapefruit, peach, and fir forest.",[c("grapefruit",40),c("sweet-peach",30),c("yolka",30)]),
 m("648","coconut-candy-pistachio","Кокосовая коровка","Coconut Candy Pistachio","Кокос, сливочная карамель и фисташка.","Coconut, creamy caramel, and pistachio.",[c("coconut-shake",40),c("candy-cow",30),c("pistachio",30)]),
 m("581","frosty-grapefruit-orange","Морозный цитрус","Frosty Citrus","Охлаждение с грейпфрутом и апельсином.","Cooling with grapefruit and orange.",[c("frosty",40),c("grapefruit",30),c("orange-team",30)]),
 m("467","melonade-berry-estragon","Мелонад с ягодами и эстрагоном","Melonade Berry Estragon","Мелонад, ягодные леденцы и эстрагон.","Melonade, berry candy, and estragon.",[c("melonade",40),c("berry-holls",30),c("estragon",30)]),
 m("809","feijoa-kiwi","Фейхоа и киви","Feijoa Kiwi","Кисло-сладкий дуэт фейхоа и киви.","A sweet-and-sour feijoa and kiwi duo.",[c("feijoa",60),c("kiwi-smoothie",40)])
];
