import type {CatalogSource} from "./catalog-v1.js";import type {OfficialMixSeed,MixComponentSeed} from "./mixes-v1.js";
const src=(key:string,url:string,title:string,type:"editorial_recipe"|"user_recipe",author?:string):CatalogSource=>({key,url,title,publisher:"DARKSIDE",sourceType:type,author,percentageEvidence:"explicit_numeric_percentages",accessedAt:"2026-09-09",verifiedAt:"2026-09-09",confidence:"high",notes:"Source prints a numeric percentage beside every named component; no ratio conversion."});
export const mixSourcesV2:CatalogSource[]=[src("ds-root-pack","https://t.me/s/trydarkside/6233","SABOTAGE ROOT BEAR mixpack","editorial_recipe"),src("ds-liquidator-pack","https://t.me/s/trydarkside/5757","LIQUIDATOR mixpack","editorial_recipe"),src("ds-tea-battle","https://t.me/s/trydarkside/5757","DARKSIDE tea mix battle","editorial_recipe"),src("ds-mixbot-lemonade","https://darkside-world.com/products/mixbot/645005c4b905de05a5afe15e","Лимонадный микс","user_recipe","true_laputin"),src("ds-mixbot-basil","https://darkside-world.com/products/mixbot/6425b6dfb845831a7b5ffcd1","BASIL BLAST #5","editorial_recipe")];
const c=(product:string,percentage:number):MixComponentSeed=>({product,percentage});const d=(slug:string)=>`darkside/core/${slug}`,s=(slug:string)=>`sabotage/original/${slug}`,st=(slug:string)=>`starline/original/${slug}`;
const m=(slug:string,ru:string,en:string,sourceKey:string,components:MixComponentSeed[]):OfficialMixSeed=>({slug,titleRu:ru,titleEn:en,summaryRu:ru,summaryEn:en,translationOrigin:"normalized_translation",sourceKey,components});
export const officialMixesV2:OfficialMixSeed[]=[
 m("root-bear-sweet","Сладкий Root Bear","Sweet Root Bear","ds-root-pack",[c(s("root-bear"),50),c(d("blackcurrant"),30),c(st("cherry"),20)]),m("root-bear-fresh","Свежий Root Bear","Fresh Root Bear","ds-root-pack",[c(s("root-bear"),40),c(d("green-beam"),40),c(d("bloody-orange"),20)]),m("root-bear-sour","Кислый Root Bear","Sour Root Bear","ds-root-pack",[c(s("root-bear"),30),c(s("acid"),40),c(d("yagoda-malina"),30)]),m("root-bear-spicy","Пряный Root Bear","Spicy Root Bear","ds-root-pack",[c(s("root-bear"),40),c(s("shaolime"),30),c(d("bloody-orange"),30)]),
 m("liquidator-sweet","Сладкий Liquidator","Sweet Liquidator","ds-liquidator-pack",[c(s("liquidator"),30),c(d("bananapapa"),35),c(d("killer-milk"),10),c(st("papaya"),25)]),m("liquidator-fresh","Свежий Liquidator","Fresh Liquidator","ds-liquidator-pack",[c(s("liquidator"),85),c(d("supernova"),15)]),m("liquidator-sour","Кислый Liquidator","Sour Liquidator","ds-liquidator-pack",[c(s("liquidator"),25),c(d("cherry-rocks"),30),c(d("cream-soda"),15),c(s("acid"),15),c(d("cosmo-flower"),15)]),m("liquidator-spicy","Пряный Liquidator","Spicy Liquidator","ds-liquidator-pack",[c(s("liquidator"),40),c(st("cream"),30),c(s("pinekiller"),30)]),
 m("black-tea-lime-currant","Чёрный чай с лаймом и смородиной","Black Tea with Lime and Currant","ds-tea-battle",[c(d("bergamonstr"),20),c(d("redberry"),45),c(d("lime-up"),30),c(d("honey-dust"),5)]),m("ural-berry-tea","Уральский ягодный чай","Ural Berry Tea","ds-tea-battle",[c(d("generis-raspberry"),35),c(d("bergamonstr"),30),c(d("red-zeppelin"),10),c(d("red-tea"),25)]),
 m("darkside-lemonade","Лимонадный микс","Lemonade Mix","ds-mixbot-lemonade",[c(d("red-alert"),50),c(d("pear"),30),c(d("kalee-grapefruit-2"),20)]),m("basil-blast-five","Basil Blast №5","Basil Blast No. 5","ds-mixbot-basil",[c(d("basil-blast"),10),c(d("cream-soda"),30),c(d("red-tea"),20),c(d("blackcurrant"),40)])
];
