// Generated by npm run catalog:refresh:musthave. Commerce, stock, packaging and media excluded.
import type {MusthaveSnapshot} from "../src/musthaveRefresh.js";
export const musthaveSnapshot:MusthaveSnapshot={
  "source": {
    "categoryUrl": "https://musthave.ru/category/tabak-dlya-kalyana/",
    "accessedAt": "2026-09-10",
    "verifiedAt": "2026-09-10",
    "publisher": "MUSTHAVE",
    "pages": 9
  },
  "products": [
    {
      "uid": "/tabak-dlya-kalyana-musthave-alova/",
      "slug": "alova",
      "title": "Alova",
      "flavorNoteRu": "Алоэ и розовая гуава",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-apple-drops/",
      "slug": "apple-drops",
      "title": "Apple Drops",
      "flavorNoteRu": "Яблочные леденцы",
      "tags": [
        "cooling",
        "apple",
        "candy"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-araram/",
      "slug": "araram",
      "title": "Araram",
      "flavorNoteRu": "Арбуз, виноград, чернослив",
      "tags": [
        "grape",
        "watermelon",
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-baikal/",
      "slug": "baikal",
      "title": "Baikal",
      "flavorNoteRu": "Лесные травы и хвоя",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-banana-mama/",
      "slug": "banana-mama",
      "title": "Banana Mama",
      "flavorNoteRu": "Банан",
      "tags": [
        "banana"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-barberry-candy/",
      "slug": "barberry-candy",
      "title": "Barberry Candy",
      "flavorNoteRu": "Барбарисовые конфеты",
      "tags": [
        "berry",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-berry-holls/",
      "slug": "berry-holls",
      "title": "Berry Holls",
      "flavorNoteRu": "Ягодные леденцы",
      "tags": [
        "cooling",
        "berry",
        "candy"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-berry-mors/",
      "slug": "berry-mors",
      "title": "Berry Mors",
      "flavorNoteRu": "Ягодный морс",
      "tags": [
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-black-currant/",
      "slug": "black-currant",
      "title": "Black Currant",
      "flavorNoteRu": "Чёрная смородина",
      "tags": [
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-smirodina-apilsin-vinograd/",
      "slug": "currant-orange-grape",
      "title": "Black Orange",
      "flavorNoteRu": "Смородина, апельсин и виноград",
      "tags": [
        "orange",
        "berry",
        "grape"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-blackberry/",
      "slug": "blackberry",
      "title": "Blackberry",
      "flavorNoteRu": "Ежевика",
      "tags": [
        "blackberry",
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-golybika-limon-myata/",
      "slug": "blue-blast",
      "title": "Blue Blast",
      "flavorNoteRu": "Голубика, лимон и мята",
      "tags": [
        "lemon",
        "mint"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-blueberry/",
      "slug": "blueberry",
      "title": "Blueberry",
      "flavorNoteRu": "Черника",
      "tags": [
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cacao/",
      "slug": "cacao",
      "title": "Cacao",
      "flavorNoteRu": "Какао и маршмеллоу",
      "tags": [
        "cacao",
        "candy"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-candy-cow/",
      "slug": "candy-cow",
      "title": "Candy Cow",
      "flavorNoteRu": "Сливочная карамель",
      "tags": [
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-caribbean-rum/",
      "slug": "caribbean-rum",
      "title": "Caribbean Rum",
      "flavorNoteRu": "Карибский ром",
      "tags": [
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-charlotte-pie/",
      "slug": "charlotte-pie",
      "title": "Charlotte Pie",
      "flavorNoteRu": "Яблочный пирог",
      "tags": [
        "pastry",
        "apple"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cheesecake/",
      "slug": "cheesecake",
      "title": "Cheesecake",
      "flavorNoteRu": "Чизкейк",
      "tags": [
        "cream",
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cherry-juice/",
      "slug": "cherry-juice",
      "title": "Cherry Juice",
      "flavorNoteRu": "Вишнёвый сок",
      "tags": [
        "cherry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cherry-cola/",
      "slug": "cherry-cola",
      "title": "Cherry-Cola",
      "flavorNoteRu": "Вишнёвая кола",
      "tags": [
        "cherry",
        "cola"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-choco-mint/",
      "slug": "choco-mint",
      "title": "Choco-Mint",
      "flavorNoteRu": "Шоколад и мята",
      "tags": [
        "mint",
        "cacao",
        "cola"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cinnamon-roll/",
      "slug": "cinnamon-roll",
      "title": "Cinnamon Roll",
      "flavorNoteRu": "Булочка с корицей",
      "tags": [
        "spices"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-citrus-spritz/",
      "slug": "citrus-spritz",
      "title": "Citrus Spritz",
      "flavorNoteRu": "Цитрусовый коктейль",
      "tags": [
        "citrus",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-coconut-shake/",
      "slug": "coconut-shake",
      "title": "Coconut Shake",
      "flavorNoteRu": "Кокосовый шейк",
      "tags": [
        "coconut"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cola/",
      "slug": "cola",
      "title": "Cola",
      "flavorNoteRu": "Кола",
      "tags": [
        "cola"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cookie/",
      "slug": "cookie",
      "title": "Cookie",
      "flavorNoteRu": "Шоколадное печенье",
      "tags": [
        "cacao",
        "cola"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cranberry/",
      "slug": "cranberry",
      "title": "Cranberry",
      "flavorNoteRu": "Клюква",
      "tags": [
        "cranberry",
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cream-soda/",
      "slug": "cream-soda",
      "title": "Cream Soda",
      "flavorNoteRu": "Крем сода",
      "tags": [
        "cream",
        "beverage"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-cucunade/",
      "slug": "cucunade",
      "title": "Cucunade",
      "flavorNoteRu": "Огуречный лимонад",
      "tags": [
        "lemon",
        "beverage",
        "cucumber"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-earl-grey/",
      "slug": "earl-grey",
      "title": "Earl Grey",
      "flavorNoteRu": "Чай Эрл Грей",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-elderberry/",
      "slug": "elderberry",
      "title": "Elderberry",
      "flavorNoteRu": "Бузина",
      "tags": [
        "berry",
        "elderberry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-estragon/",
      "slug": "estragon",
      "title": "Estragon",
      "flavorNoteRu": "Эстрагон",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-feijoa/",
      "slug": "feijoa",
      "title": "Feijoa",
      "flavorNoteRu": "Фейхоа",
      "tags": [
        "feijoa"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-fizzy-dizzy/",
      "slug": "fizzy-dizzy",
      "title": "Fizzy Dizzy",
      "flavorNoteRu": "Шампанское и барбарис",
      "tags": [
        "candy",
        "grape",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-forest-berries/",
      "slug": "forest-berries",
      "title": "Forest Berries",
      "flavorNoteRu": "Лесные ягоды",
      "tags": [
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-frosty/",
      "slug": "frosty",
      "title": "Frosty",
      "flavorNoteRu": "Охлаждающий",
      "tags": [
        "cooling"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-garnet-grape/",
      "slug": "garnet-grape",
      "title": "Garnet Grape",
      "flavorNoteRu": "Гранат и виноград",
      "tags": [
        "grape",
        "pomegranate"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-gooseberry/",
      "slug": "gooseberry",
      "title": "Gooseberry",
      "flavorNoteRu": "Крыжовник",
      "tags": [
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-grapefruit/",
      "slug": "grapefruit",
      "title": "Grapefruit",
      "flavorNoteRu": "Грейпфрут",
      "tags": [
        "grapefruit",
        "grape"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-green-fizz/",
      "slug": "green-fizz",
      "title": "Green Fizz",
      "flavorNoteRu": "Киви, кактус и абсент",
      "tags": [
        "beverage",
        "tropical-fruit",
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-grusha-limon-tarkhun/",
      "slug": "green-tonic",
      "title": "Green Tonic",
      "flavorNoteRu": "Груша, лимон и тархун",
      "tags": [
        "lemon",
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-kiwi-yabloko-laim/",
      "slug": "greendizer",
      "title": "Greendizer",
      "flavorNoteRu": "Киви, яблоко и лайм",
      "tags": [
        "apple",
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-guanapapa/",
      "slug": "guanapapa",
      "title": "Guanapapa",
      "flavorNoteRu": "Гуанабана и папайя",
      "tags": [
        "papaya"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-holland-pie/",
      "slug": "holland-pie",
      "title": "Holland Pie",
      "flavorNoteRu": "Голландский пирог",
      "tags": [
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-honey-holls/",
      "slug": "honey-holls",
      "title": "Honey Holls",
      "flavorNoteRu": "Медовые леденцы",
      "tags": [
        "cooling",
        "honey",
        "candy"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-ice-cream/",
      "slug": "ice-cream",
      "title": "Ice Cream",
      "flavorNoteRu": "Мороженое",
      "tags": [
        "cooling",
        "cream",
        "ice-cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-ice-mint/",
      "slug": "ice-mint",
      "title": "Ice Mint",
      "flavorNoteRu": "Освежающая мята",
      "tags": [
        "cooling",
        "mint"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-jumango/",
      "slug": "jumango",
      "title": "Jumango",
      "flavorNoteRu": "Манго, малина и мёд",
      "tags": [
        "raspberry",
        "tropical-fruit",
        "honey"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-kiwi-smoothie/",
      "slug": "kiwi-smoothie",
      "title": "Kiwi Smoothie",
      "flavorNoteRu": "Киви-смузи",
      "tags": [
        "beverage",
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-lemon-pie/",
      "slug": "lemon-pie",
      "title": "Lemon Pie",
      "flavorNoteRu": "Лимонный пирог",
      "tags": [
        "lemon",
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-lemon-tonic/",
      "slug": "lemon-tonic",
      "title": "Lemon Tonic",
      "flavorNoteRu": "Лимонный тоник",
      "tags": [
        "lemon"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-lemon-lime/",
      "slug": "lemon-lime",
      "title": "Lemon-Lime",
      "flavorNoteRu": "Лимон и лайм",
      "tags": [
        "lemon"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-lemongrass/",
      "slug": "lemongrass",
      "title": "Lemongrass",
      "flavorNoteRu": "Лемонграсс",
      "tags": [
        "lemon"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-mad-pear/",
      "slug": "mad-pear",
      "title": "Mad Pear",
      "flavorNoteRu": "Груша",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-mandarin/",
      "slug": "mandarin",
      "title": "Mandarin",
      "flavorNoteRu": "Мандарин",
      "tags": [
        "orange"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-mango-sling/",
      "slug": "mango-sling",
      "title": "Mango Sling",
      "flavorNoteRu": "Манго-слинг",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-maple-pecan/",
      "slug": "maple-pecan",
      "title": "Maple Pecan",
      "flavorNoteRu": "Кленовый пекан",
      "tags": [
        "maple",
        "pecan"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-marula/",
      "slug": "marula",
      "title": "Marula",
      "flavorNoteRu": "Марула",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-masala-tea/",
      "slug": "masala-tea",
      "title": "Masala Tea",
      "flavorNoteRu": "Чай масла",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-melonade/",
      "slug": "melonade",
      "title": "Melonade",
      "flavorNoteRu": "Мелонад",
      "tags": [
        "watermelon",
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-milk-oolong/",
      "slug": "milk-oolong",
      "title": "Milk Oolong",
      "flavorNoteRu": "Молочный улун",
      "tags": [
        "beverage",
        "cream",
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-milky-rice/",
      "slug": "milky-rice",
      "title": "Milky Rice",
      "flavorNoteRu": "Рисовая каша",
      "tags": [
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-morocco/",
      "slug": "morocco",
      "title": "Morocco",
      "flavorNoteRu": "Марокканский чай",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-mulled-wine/",
      "slug": "mulled-wine",
      "title": "Mulled Wine",
      "flavorNoteRu": "Глинтвейн",
      "tags": [
        "grape",
        "beverage",
        "spices"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-nord-star/",
      "slug": "nord-star",
      "title": "Nord Star",
      "flavorNoteRu": "Кислая вишня",
      "tags": [
        "cherry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-orange-team/",
      "slug": "orange-team",
      "title": "Orange Team",
      "flavorNoteRu": "Апельсин и мандарин",
      "tags": [
        "orange",
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-paradise/",
      "slug": "paradise",
      "title": "Paradise",
      "flavorNoteRu": "Банан, кокос и карамель",
      "tags": [
        "banana",
        "coconut"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-passion-plum/",
      "slug": "passion-plum",
      "title": "Passion Plum",
      "flavorNoteRu": "Слива и маракуйя",
      "tags": [
        "passion-fruit",
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-pearl-pool/",
      "slug": "pearl-pool",
      "title": "Pearl Pool",
      "flavorNoteRu": "Моринга и тропические фрукты",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-pineapple-rings/",
      "slug": "pineapple-rings",
      "title": "Pineapple Rings",
      "flavorNoteRu": "Ананасовый колечки",
      "tags": [
        "apple",
        "pineapple"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-pinkman/",
      "slug": "pinkman",
      "title": "Pinkman",
      "flavorNoteRu": "Пинкман",
      "tags": [
        "berry",
        "citrus"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-pistachio/",
      "slug": "pistachio",
      "title": "Pistachio",
      "flavorNoteRu": "Фисташка",
      "tags": [
        "pecan"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-pistachio-cake/",
      "slug": "pistachio-cake",
      "title": "Pistachio Cake",
      "flavorNoteRu": "Фисташковый пирог",
      "tags": [
        "pastry",
        "pecan"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-prosecco/",
      "slug": "prosecco",
      "title": "Prosecco",
      "flavorNoteRu": "Просекко",
      "tags": [
        "grape",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-quince/",
      "slug": "quince",
      "title": "Quince",
      "flavorNoteRu": "Айва",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-raspberry/",
      "slug": "raspberry",
      "title": "Raspberry",
      "flavorNoteRu": "Малина",
      "tags": [
        "raspberry",
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-red-bomb/",
      "slug": "red-bomb",
      "title": "Red Bomb",
      "flavorNoteRu": "Гранат",
      "tags": [
        "pomegranate"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-klybnika-limon-arbuz/",
      "slug": "red-rush",
      "title": "Red Rush",
      "flavorNoteRu": "Клубника, лимон и арбуз",
      "tags": [
        "lemon",
        "strawberry",
        "watermelon"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-red-tea/",
      "slug": "red-tea",
      "title": "Red Tea",
      "flavorNoteRu": "Красный чай",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-rocketman/",
      "slug": "rocketman",
      "title": "Rocketman",
      "flavorNoteRu": "Рокетмен",
      "tags": [
        "strawberry",
        "grapefruit",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-ruby-grape/",
      "slug": "ruby-grape",
      "title": "Ruby Grape",
      "flavorNoteRu": "Виноград и мята",
      "tags": [
        "grape",
        "mint"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sea-backthorn-tea/",
      "slug": "sea-buckthorn-tea",
      "title": "Sea Buckthorn Tea",
      "flavorNoteRu": "Облепиховый чай",
      "tags": [
        "herbal"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-klybnishnyi-sorbet/",
      "slug": "sorbetto",
      "title": "Sorbetto",
      "flavorNoteRu": "Клубничный сорбет",
      "tags": [
        "strawberry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sour-apple/",
      "slug": "sour-apple",
      "title": "Sour Apple",
      "flavorNoteRu": "Кислое яблоко",
      "tags": [
        "apple"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sour-berries/",
      "slug": "sour-berries",
      "title": "Sour Berries",
      "flavorNoteRu": "Кислые ягоды",
      "tags": [
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sour-citrus/",
      "slug": "sour-citrus",
      "title": "Sour Citrus",
      "flavorNoteRu": "Кислые цитрусы",
      "tags": [
        "citrus"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sour-tropic/",
      "slug": "sour-tropic",
      "title": "Sour Tropic",
      "flavorNoteRu": "Кислые тропики",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-space-flavour/",
      "slug": "space-flavour",
      "title": "Space Flavour",
      "flavorNoteRu": "Манго, маракуйя, личи и роза",
      "tags": [
        "passion-fruit",
        "lychee",
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-strawberry/",
      "slug": "strawberry",
      "title": "Strawberry",
      "flavorNoteRu": "Клубника",
      "tags": [
        "strawberry",
        "berry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-strawberry-lychee/",
      "slug": "strawberry-lychee",
      "title": "Strawberry-Lychee",
      "flavorNoteRu": "Земляника и личи",
      "tags": [
        "strawberry",
        "berry",
        "lychee"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sweet-melon/",
      "slug": "sweet-melon",
      "title": "Sweet Melon",
      "flavorNoteRu": "Дыня",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-sweet-peach/",
      "slug": "sweet-peach",
      "title": "Sweet Peach",
      "flavorNoteRu": "Персик",
      "tags": [
        "peach"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-tipsy/",
      "slug": "tipsy",
      "title": "Tipsy",
      "flavorNoteRu": "Ягодный коктейль",
      "tags": [
        "berry",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-tropic-juice/",
      "slug": "tropic-juice",
      "title": "Tropic Juice",
      "flavorNoteRu": "Тропический сок",
      "tags": [
        "tropical-fruit"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "pronounced"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-unicorn-treats/",
      "slug": "unicorn-treats",
      "title": "Unicorn Treats",
      "flavorNoteRu": "Кукурузные палочки и безе",
      "tags": [
        "candy",
        "pastry"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-vanilla-cream/",
      "slug": "vanilla-cream",
      "title": "Vanilla Cream",
      "flavorNoteRu": "Ванильный крем",
      "tags": [
        "cream"
      ],
      "sweetness": "pronounced",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-violet/",
      "slug": "violet",
      "title": "Violet",
      "flavorNoteRu": "Экзотический лимонад",
      "tags": [
        "lemon",
        "tropical-fruit",
        "beverage"
      ],
      "sweetness": "subtle",
      "acidity": "pronounced",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-watermelon/",
      "slug": "watermelon",
      "title": "Watermelon",
      "flavorNoteRu": "Арбуз",
      "tags": [
        "watermelon"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    },
    {
      "uid": "/tabak-dlya-kalyana-musthave-yolka/",
      "slug": "yolka",
      "title": "Yolka",
      "flavorNoteRu": "Хвойный лес",
      "tags": [
        "fir"
      ],
      "sweetness": "subtle",
      "acidity": "subtle",
      "freshness": "subtle"
    }
  ]
};
